trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>LastViewedDate__c</fullName>
        <label>LastViewedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/DiscussionWidgetMostReadController.cls
/**
*@author Juan Bessonart @ 06/02/2008
*/
public class DiscussionWidgetMostReadController {
	
	/**
	* Get more readed topics
	*@return List<DiscussionTopic__c>
	*/
	public List<DiscussionTopic__c> getMostRead () {
		List<DiscussionTopic__c> mostRead = new List<DiscussionTopic__c>();
		mostRead = [select Id, Subject__c, ViewCount__c, LastViewedDate__c from DiscussionTopic__c order by LastViewedDate__c desc limit 5];
		return mostRead;
	}

}