trunk/objects/DiscussionForum__c.object
<CustomObject>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.1/src/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.1/src/classes/TeamsWidgetActiveDiscussionsTest.cls
public class TeamsWidgetActiveDiscussionsTest {

	public static testMethod void testTeam() {
	TeamsWidgetActiveDiscussionsController team = new TeamsWidgetActiveDiscussionsController();
	List<DiscussionTopic__c> discussions;
	DiscussionForum__c forum;
	Id teamspaceId;
	Integer actdisSize;
	String userId = UserInfo.getUserId();
    Boolean previleges=team.getnewPrivileges();
    System.assert(previleges==false,'El usuario no tiene TeamMember');
	DiscussionTopic__c dis = new DiscussionTopic__c();
	TeamsWidgetActiveDiscussionsController.Discussion disc= new	TeamsWidgetActiveDiscussionsController.Discussion(dis);
	team.getDiscussions();	
	//System.assert(list.size()<0,'La lista no tiene elementos');	
	Datetime d =System.now();
	String fecha= disc.formatDateToText(d);
	System.assert(fecha=='Today ','OK'); 	
	
	}
}