trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.1/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

0.1/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamRelationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateDiscussionTopics__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateDiscussionTopics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageDiscussionForums__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageDiscussionForums</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostDiscussionTopicReplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostDiscussionTopicReplies</label>
        <type>Checkbox</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.1/src/classes/DiscussionTopicTest.cls
public class DiscussionTopicTest {

  	public static Boolean sortByDesc = false;
	public static String sortBy = 'LastPostedMessage__c';
	public static String USERID = UserInfo.getUserId();
	
	public static testMethod void testDiscussion() {
	
	DiscussionTopicsController dis= new  DiscussionTopicsController ();
	List<DiscussionTopicsController.TopicList> topicList =dis.fillTopicList();
	DiscussionTopicsController.TopicList top = new DiscussionTopicsController.TopicList();
	
	DiscussionMessage__c[] disMessage= [Select id from DiscussionMessage__c]; 
	
	String info = top.lastPostInfoString(disMessage[0].id);
	List<TeamMember__c> userTeams = new List<TeamMember__c>();
	userTeams = [SELECT Team__c, TeamProfile__c FROM TeamMember__c WHERE User__c =: USERID];
   
    TeamMember__c teams = userTeams.get(0);
    
    List<TeamProfile__c> profileList=[SELECT CreateDiscussionTopics__c,ManageDiscussionForums__c,PostDiscussionTopicReplies__c FROM TeamProfile__c WHERE id=: teams.TeamProfile__c];
    TeamProfile__c profile = profileList.get(0);

    boolean createDiscussionTopics = profile.createDiscussionTopics__c;
	System.assert(createDiscussionTopics==true,'Tiene Discussion Topics ');
	boolean manageDiscussionForums= profile.ManageDiscussionForums__c;
	System.assert(createDiscussionTopics==false,'Tiene Manage Discussion ');
	boolean postDiscussionTopicReplies= profile.PostDiscussionTopicReplies__c;
	System.assert(createDiscussionTopics==false,'Tiene Discussion Topics ');
	/*
	
		para este usuario
		conseguir el team member Id de el usuario 
		consegui el team profile Id para ese team member Id
		fijarse que persmisos tiene y assertar para cada caso ABM para ese usuario.
	*/
	
	
	System.assert(info==null,'No existe info');
	DiscussionForum__c disForum =  dis.getForumData();
	dis.saveTopic ();
	List<DiscussionTopic__c> lisDis= dis.getMostRead ();
	boolean permiso = dis.getPermissionAuthorApex();
	System.assert(permiso==false,'No tiene permiso');
	boolean isTeamAdminMember = dis.getIsTeamAdminMember();
	
	String resultSort= dis.getSortBy ();
	System.assert(sortBy=='lastReplies','OK');
	dis.sortList () ;
	
	}	
	
	
	
}