trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/DiscussionOverlayTopicEdit.cls
/**
*@author: Bruno Fagundez @ 05-30-2008
*/
public without sharing class DiscussionOverlayTopicEdit {
	
	/**
	* Constructor
	*/
	public DiscussionOverlayTopicEdit () {}
	
	/**
	* Get Team__c Id
	*@return String
	*/
	public String getTeamId () {
		return TEAMID;
	}

	/**
	* Method for do Dummy refresh.
	*/
	public void dummyRefresh(){}
		
	public String TEAMID = System.currentPageReference().getParameters().get('id');
	public DiscussionForum__c forum = new DiscussionForum__c();

	/**
	* Get the forum data 
	*@return DiscussionForum__c
	*/	
	public DiscussionForum__c getForumData(){
   		if(TEAMID != null){
   			 try {
   			 	forum = [SELECT
   						Team__r.Name, 
   						Team__c,
   						Id 
   						FROM DiscussionForum__c WHERE Team__c =: TEAMID LIMIT 1];
   			 } catch (Exception e) {
   			 	throw e;
   			 }   			    			 
   		} else {
   			forum = null;
   		}
   		return forum;
   	}   	
   	
   	DiscussionTopic Topic = new DiscussionTopic(); 
   	/**
   	* Get DiscussionTopic Instance
   	*@return DiscussionTopic
   	*/
   	public DiscussionTopic getTopic(){
   		return Topic;
   	}
   	
   	/**
   	* Set DiscussionTopic instance
   	*@param DiscussionTopic
   	*/
   	public void setTopic (DiscussionTopic dt){
   		Topic = dt;
   	}
   	
   	/**
	* Read current Forum and Save the topic
	*/   	
   	public void saveTopic(){
   		//Read forum
   		getForumData();
   		// Build and Insert the Topic first
   		DiscussionTopic__c newTopic = new DiscussionTopic__c();
   		newTopic.Subject__c = Topic.Name;	
		newTopic.Team__c = TEAMID;
		newTopic.DiscussionForum__c = forum.Id;
   		insert newTopic;
   		// Build and insert First Message 
   		DiscussionMessage__c firstMessage = new DiscussionMessage__c();
   		firstMessage.Discussiontopic__c = newTopic.Id;
		firstMessage.Team__c = TEAMID;
		firstMessage.Message__c = Topic.Text;
   		insert firstMessage;
   	}

   	/**
	* Read current Forum and Update the topic
	*/   	
   	public void updateTopic(){
   		// Update the Topic 
   		DiscussionTopic__c topicToEdit = [Select Subject__c from DiscussionTopic__c where Id =: Topic.TopicIdToUpdate];
   		topicToEdit.Subject__c = Topic.Name;	
   		update topicToEdit;
   		// Update the topic First Message 
   		DiscussionMessage__c messageToUpdate = [ Select Message__c from DiscussionMessage__c where Id =: Topic.MessageIdToUpdate ];
   		messageToUpdate.Message__c = Topic.Text;			
   		update messageToUpdate;
   	}

	/**
	* DiscussionTopic class
	*@author Bruno Fagundez
	*/	
   	public class DiscussionTopic {   
   		public String TopicIdToUpdate {get; set;}	
   		public String MessageIdToUpdate {get; set;}
   		public String Name {get; set;}
   		public String Text {get; set;}
   	}
}