trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.1/src/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

branches/0.1/src/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.5/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.2/src/classes/DiscussionTopicTest.cls
@IsTest private class DiscussionTopicTest {
    
    public static testMethod void testDiscussion() {
        try{

            DiscussionTopicsController dis= new DiscussionTopicsController();
            
            DiscussionTopic__c dt = [select d.Team__c from DiscussionTopic__c d limit 1];
            dis.setTEAMID('');
            dis.refreshList();
            Boolean b = dis.getNoTopics();
            List<DiscussionTopicsController.TopicList> topics = dis.getTopicList();

            DiscussionTopicsController.updateviewCount upd = new DiscussionTopicsController.updateviewCount();
            String topicId = upd.getTopicId();
            upd.updateviewCountRedirect();
            PageReference pr = upd.getTopicPage();
            
            PageReference pr2 = dis.openTopic();
            
            DiscussionTopicsController.TopicList topicList = new DiscussionTopicsController.TopicList();
            topicList.setId('Some Id');
            topicList.setAuthorId('Some Id');
            topicList.setAuthorName('Some Name');
            topicList.setName('Some Name');
            topicList.setTeamName('Team Name');
            topicList.setTeamId('Some team');
            topicList.setNumberOfMessages(1);
            topicList.setNumberOfViews(1);

            DiscussionMessage__c dsMessage = [select Id from DiscussionMessage__c limit 1];
            topicList.setLastPostMessage(dsMessage.Id);
            topicList.setFirstMessageCreated(dsMessage);
            topicList.setAuthorPicture('Some Author');
            topicList.setEnableActions('Some Id', true);
            
            Boolean b2 = topicList.getEnableActions();
            String pic = topicList.getAuthorPicture();
            
            //String message = topicList.getFirstMessageCreated();
            //String firstId = topicList.getFirstMessageId();
            
            String id = topicList.getId();
            String author = topicList.getAuthorId();
            String fuulAuthor = topicList.getFullAuthorName();
            String authorName = topicList.getAuthorName();
            String name = topicList.getName();
            String shortName = topicList.getShortName();
            String teamName = topicList.getTeamName();
            String teamId = topicList.getTeamId();
            Integer nMessage = topicList.getNumberOfMessages();
            Integer nView = topicList.getNumberOfViews();
            String lastPost = topicList.getLastPostMessage();
            Boolean isAuthor = topicList.getIsAuthor();
            
            dis.nextPage();
            dis.prevPage();
            dis.genCntPagination();
            Integer nAux = dis.getCurrentPagination();
            nAux = dis.getNumberOfItemsToShow();
            nAux = dis.getFirstRow();
            Boolean bAux = dis.getPrevPageLinkShow();
            bAux = dis.getPrevPageShow();
            bAux = dis.getNextPageLinkShow();
            bAux = dis.getNextPageShow();
            
            dis.setTEAMID(dt.Team__c);
            dis.saveTopic();            
            dis.updateReadCount();
            DiscussionForum__c forum = dis.getForumData();
            dis.fillTopicList();
            dis.getMostRead();
            dis.genPermissions();
            dis.getUserPermissions();
            dis.saveTopic();            
            
            String sortBy = null;
            
            dis.setSortBy('Name');
            dis.setSortByDesc(false);
            dis.sortList();
            
            dis.setSortByDesc(true);
            dis.sortList();
            sortBy = dis.getSortBy();
            
            dis.setSortBy('PostedBy__r.Name');
            dis.setSortByDesc(false);
            dis.sortList();
            
            dis.setSortByDesc(true);
            dis.sortList();         
            sortBy = dis.getSortBy();
            
            dis.setSortBy('ViewCount__c');
            dis.sortList();
            sortBy = dis.getSortBy();
            
            dis.setSortBy('MessageCount__c');
            dis.setSortByDesc(false);
            dis.sortList();
            
            dis.setSortByDesc(true);
            dis.sortList();                                     
            sortBy = dis.getSortBy();
            
            dis.setSortBy('LastPostedMessage__c');
            dis.setSortByDesc(false);
            dis.sortList();
            
            dis.setSortByDesc(true);
            dis.sortList();     
            sortBy = dis.getSortBy();
            
        }catch(Exception e){
            throw e;
        }
    }   
}