trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.1/src/classes/DiscussionCreatedDataController.cls
public class DiscussionCreatedDataController {
	
	public void updateData () {
		List<DiscussionMessage__c> messageList = [select Id, CreatedById, CreatedDate, PostedBy__c, PostedDate__c from DiscussionMessage__c];
		for (DiscussionMessage__c item: messageList) {
				item.PostedBy__c = item.CreatedById;
				item.PostedDate__c = item.CreatedDate; 
		}
		update messageList;
		
		List<DiscussionTopic__c> topicList = [select Id, CreatedById, CreatedDate, PostedBy__c, PostedDate__c from DiscussionTopic__c];
		for (DiscussionTopic__c item: topicList) {
				item.PostedBy__c = item.CreatedById;
				item.PostedDate__c = item.CreatedDate; 
		}
		update topicList;
	}
}