trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Employer__c.object
<CustomObject>
    <description>Store the employers of every user.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State__c</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Employer</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/EmploymentHistory__c.object
<CustomObject>
    <fields>
        <fullName>Employer__c</fullName>
        <description>Employer</description>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Employment  History</relationshipLabel>
        <relationshipName>Employer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsCurrentJob__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCurrentJob</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkedFrom__c</fullName>
        <label>Worked From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkedTo__c</fullName>
        <label>Worked To</label>
        <type>Date</type>
    </fields>
    <label>Employment  History</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment  History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/ProjectTaskPred__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipLabel>Project Task Predecessors (Parent)</relationshipLabel>
        <relationshipName>Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <label>Predecessor</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectTaskPred</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Preds</relationshipLabel>
        <relationshipName>ProjectPreds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task Predecessor</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Predecessor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Predecessors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>NewMemberProfile__c</fullName>
        <label>NewMemberProfile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateBlogs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateBlogs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateBookmarks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateBookmarks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateDiscussionTopics__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateDiscussionTopics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateProjectTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateProjectTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateWikiPages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateWikiPages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageBlogs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageBlogs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageBookmarks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageBookmarks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageDiscussionForums__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageDiscussionForums</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageProjectTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageProjectTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageTeams__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageTeams</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageWikis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageWikis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostBlogComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostBlogComments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostBookmarkComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostBookmarkComments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostDiscussionTopicReplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostDiscussionTopicReplies</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostWikiComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostWikiComments</label>
        <type>Checkbox</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/WikiLink__c.object
<CustomObject>
    <fields>
        <fullName>FromLink__c</fullName>
        <label>FromLink</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>WikiLinks (FromLink)</relationshipLabel>
        <relationshipName>FromLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Wiki Links</relationshipLabel>
        <relationshipName>WikiLinks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ToLink__c</fullName>
        <label>ToLink</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>WikiLinks (ToLink)</relationshipLabel>
        <relationshipName>ToLink</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Link</label>
    <nameField>
        <label>WikiLink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiLinks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>PageCreatedBy__c</fullName>
        <label>PageCreatedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiRecentlyViewed__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Wiki Recently Viewed</relationshipLabel>
        <relationshipName>WikiRecentlyViewed</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>WikiPage</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Wiki Recently Viewed</relationshipLabel>
        <relationshipName>RecentlyViewed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Recently Viewed</label>
    <nameField>
        <label>Recenty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Recently Viewed</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/TriggersTest.cls
@IsTest private class TriggersTest {

	public static testMethod void test() {
	 	GenerateEnvironmentTest.gen();
        Test.startTest();
    	// Create a new WikiRecentlyViewed Object
    	WikiPage__c newWiki = GenerateEnvironmentTest.newWiki;
    	WikiRecentlyViewed__c newWikiRecentlyViewed = new WikiRecentlyViewed__c();
    	newWikiRecentlyViewed.User__c = newWiki.PageCreatedBy__c;
    	newWikiRecentlyViewed.Name = newWiki.Name;
    	newWikiRecentlyViewed.Team__c = newWiki.Team__c;
    	newWikiRecentlyViewed.WikiPage__c = newWiki.Id;
    	upsert newWikiRecentlyViewed;
    	// Create a new WikiLink Object
    	WikiLink__c  newWikiLink = new WikiLink__c ();
    	newWikiLink.Name = newWiki.Name;
    	newWikiLink.Team__c = newWiki.Team__c;
    	newWikiLink.ToLink__c = newWiki.Id;
    	newWikiLink.FromLink__c = newWiki.Id;
    	upsert newWikiLink;
    	// Create a new ProjectTaskPred Object
    	ProjectTask__c newTask = GenerateEnvironmentTest.newTask;
    	
    	ProjectTaskPred__c newTaskPred = new ProjectTaskPred__c();
    	newTaskPred.Name = 'Foo Task Predecessor';
    	newTaskPred.Team__c = GenerateEnvironmentTest.newTeam.Id;
    	newTaskPred.Predecessor__c = newTask.Id;
    	newTaskPred.Parent__c = newTask.Id;
    	upsert newTaskPred;
    	
    	// Delete Project Task
    	delete newTask;
        
        Test.stopTest();	
	}
	
	public static testMethod void test2() {
		GenerateEnvironmentTest.gen();
        Test.startTest();
		// Update Employment History
    	Employer__c newEmployer = new Employer__c();
    	newEmployer.Name = 'Foo Employer';
    	newEmployer.City__c = 'Foo City';
    	newEmployer.Count__c = 1;
    	newEmployer.State__c = 'Foo State';
    	upsert newEmployer;
    	
    	EmploymentHistory__c newEH = new EmploymentHistory__c();
    	newEH.Name = 'Foo Name';
    	newEH.Employer__c = newEmployer.Id;
    	newEH.IsCurrentJob__c = true;
    	newEH.User__c = UserInfo.getUserId();
    	newEH.WorkedTo__c = System.today();
    	newEH.WorkedFrom__c = System.today();
    	// Set this boolean to TRUE for don't create MiniFeeds
    	TeamUtil.isTest = true;
    	upsert newEH;
    	
    	newEH.Name = 'Foo Employment History';
    	update newEH;
    	
    	TeamUtil.isTest = false;
        
        Test.stopTest();
	}
	
	public static testMethod void team() {
		
		TeamUtil.isTest = true;
		
		// Create a new Team Administrator Profile
		TeamProfile__c newTeamProfile = new TeamProfile__c();
		
		newTeamProfile.Name = 'Team Administrator';
		newTeamProfile.PostWikiComments__c = true; 
		newTeamProfile.PostDiscussionTopicReplies__c = true; 
		newTeamProfile.PostBookmarkComments__c = true; 
		newTeamProfile.PostBlogComments__c = true;  
		newTeamProfile.ManageWikis__c = true; 
		newTeamProfile.ManageTeams__c = true; 
		newTeamProfile.ManageProjectTasks__c = true; 
		newTeamProfile.ManageDiscussionForums__c = true; 
		newTeamProfile.ManageBookmarks__c = true; 
		newTeamProfile.ManageBlogs__c = true; 
		newTeamProfile.CreateWikiPages__c = true; 
		newTeamProfile.CreateProjectTasks__c = true; 
		newTeamProfile.CreateDiscussionTopics__c = true; 
		newTeamProfile.CreateBookmarks__c = true; 
		newTeamProfile.CreateBlogs__c = true;
		upsert newTeamProfile;
		
		Team__c team = new Team__c();
		
		// Create a new Team
		team.Name = 'Test class Team 2';
		team.NewMemberProfile__c = newTeamProfile.Id;
		upsert team;	
		
        Test.startTest();
		update team;
		delete team;
        	
        Test.stopTest();
	}
	
	public static testMethod void team2() {
		GenerateEnvironmentTest.gen();
        Test.startTest();
    
		TeamMember__c teamMember = [select id, Name from TeamMember__c limit 1];
		update teamMember;
		delete teamMember;
		
        Test.stopTest();
	}
	
	public static testMethod void team3() {
		GenerateEnvironmentTest.gen();
        Test.startTest();
		
		TeamProfile__c teamProfile = GenerateEnvironmentTest.newTeamProfile;
		update teamProfile;
		delete teamProfile;
    	
        Test.stopTest();
	}	
	
	public static testMethod void trigger1 () {
		GenerateEnvironmentTest.gen();
        Test.startTest();
		
		WikiPage__c sObjectRow = GenerateEnvironmentTest.newWiki;
		update sObjectRow;
		delete sObjectRow;
    	
        Test.stopTest();
	} 
	
	public static testMethod void trigger2 () {
		GenerateEnvironmentTest.gen();
        Test.startTest();
		
		ProjectTask__c sObjectRow = GenerateEnvironmentTest.newTask;
		update sObjectRow;
		delete sObjectRow;
    	
        Test.stopTest();
	} 
	
	public static testMethod void trigger3 () {
		GenerateEnvironmentTest.gen();
        Test.startTest();
		
		DiscussionMessage__c sObjectRow = GenerateEnvironmentTest.newMessage;
		update sObjectRow;
		delete sObjectRow;
    	
        Test.stopTest();
	}									
}