trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/classes/TeamsWidgetActiveDiscussionsTest.cls
@IsTest private class TeamsWidgetActiveDiscussionsTest {

	public static testMethod void testTeam() {
		try{
			GenerateEnvironmentTest.gen();
            Test.startTest();    			
			
			TeamsWidgetActiveDiscussionsController ad = new TeamsWidgetActiveDiscussionsController();
			Team__c team = GenerateEnvironmentTest.newTeam;
			ad.setTeamId(team.Id);
			ad.getTeamId();
			ad.getDiscussions();
			
			ad.setSidebar(true);
			ad.getSidebar();
			ad.getActiveDiscussionsSize();
			ad.refresh();
			List<DiscussionTopic__c> discussions = [select d.ViewCount__c, d.Subject__c, d.OwnerId, d.Name, d.MessageCount__c, 
										d.LastModifiedDate, d.LastModifiedById, d.Id, d.CreatedDate, d.CreatedById, d.PostedBy__c, 
										PostedBy__r.Name, LastPostedMessage__r.PostedBy__c, LastPostedMessage__r.PostedDate__c,
										LastPostedMessage__r.PostedBy__r.Name from DiscussionTopic__c d
								 		order by d.CreatedDate desc limit 1];
									
			TeamsWidgetActiveDiscussionsController.Discussion d = new TeamsWidgetActiveDiscussionsController.Discussion(discussions[0]);
			d.getDiscussion();
			d.getAuthor();
			d.getAuthorId();
			d.getLastPostDate();
			d.getLastReply();
			d.getLastReplyAuthorId();
			d.getLastReplyAuthor();
			d.getAuthorPicture();
			d.getViews();
			d.getReplies();
			d.formatDateToText(discussions[0].CreatedDate);
			d.formatDateToText(System.now());
			
			
			Test.stopTest();
		}catch(Exception e){
			throw e;
		}
	}
}