trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentMessage__c</fullName>
        <label>Parent Message</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <relationshipName>ParentMessage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastViewedDate__c</fullName>
        <label>LastViewedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stickied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stickied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Threaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Threaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.3/src/classes/DiscussionReplyTest.cls
@IsTest private class DiscussionReplyTest {
    public static testMethod void testDiscussion() {
         
        try{
            DiscussionReplyController dis = new DiscussionReplyController();
            DiscussionTopic__c newTopic = new DiscussionTopic__c();
            newTopic.ViewCount__c = 1;
            newTopic.Threaded__c = false;
            
            String idTeam = [select id from Team__c limit 1].id;
            newTopic.Team__c = idTeam;
            
            UserPermissionsTest.UserPermissionsTest();
            
            String idDiscussionForum = [select id from DiscussionForum__c where team__c =: idTeam limit 1].id;
            newTopic.DiscussionForum__c = idDiscussionForum;
            
            newTopic.Subject__c = 'Code Coverage';
            newTopic.Stickied__c = false;
            newTopic.PostedDate__c = System.now();
            newTopic.PostedBy__c = UserInfo.getUserId();
            newTopic.MessageCount__c = 0;
            newTopic.Locked__c = false;
            newTopic.LastViewedDate__c = System.now();
            
            insert newTopic;
            
            DiscussionMessage__c newMessage = new DiscussionMessage__c();
            newMessage.PostedDate__c = System.now();
            newMessage.Message__c = 'Replay to Topic';
            newMessage.DiscussionTopic__c = newTopic.id;
            newMessage.Team__c = idTeam;
            newMessage.Subject__c = 'Reply to Topic';
            
            insert newMessage;
            
            DiscussionMessage__c newReply = new DiscussionMessage__c();
            newReply.PostedDate__c = System.now();
            newReply.ParentMessage__c = newMessage.Id;
            newReply.Message__c = 'Reply to Message';
            newReply.DiscussionTopic__c = newTopic.id;
            newReply.Team__c = idTeam;
            newReply.Subject__c = 'Reply to Message';
            
            //insert newReply;
            
            //String idDiscussionTopic = [select id from DiscussionTopic__c limit 1].id;
            // I have to hardcode the id because it has to
            //String idDiscussionTopic = 'a0730000002qnVHAAY';
            String idDiscussionTopic = newTopic.Id;
            dis.setParamId(idDiscussionTopic);
            
            dis.setPageNumberParam('');
            
            dis.constructorMethods();
            
            if (dis.getUserPermissions() == null) {
                System.assert(true, 'Null Permissions');
            }
            
            
            if (dis.getIsTopicAuthor() == null) {
                System.assert(true, 'Null isTopicAuthor boolean');
            }   
            
            if (dis.getIsTeamAdminMember() == null) {
                System.assert(true, 'Null getIsTeamAdminMember boolean');
            }
            
            dis.saveReply();
            
            if (dis.getNoForums() == null) {
                System.assert(true, 'Null getNoForums boolean');
            }
             
            dis.setTopicIdParam(idDiscussionTopic);
            dis.updateReadCount();
            
            /* Pagination */
            dis.nextPage();
            dis.prevPage();
            dis.getCurrentPagination();
            dis.getCntPagination();
            dis.getNumberOfItemsToShow();
            dis.getFirstRow();
            dis.getPrevPageLinkShow();
            dis.getPrevPageShow();
            dis.getNextPageLinkShow();
            dis.getNextPageShow();
            
            dis.getForumData();
            dis.deleteReplyId();
            
            DiscussionReplyController.UserTopic userTopicClass = dis.getTopicUser();
            userTopicClass.getPicture();
            userTopicClass.getUser();
            userTopicClass.getTeam();
            userTopicClass.getTopic();
            userTopicClass.getMessTopic();
            userTopicClass.getStrdate();
            userTopicClass.getShowShortUserName();
            userTopicClass.getTopicNameReplaced();
            userTopicClass.getShowShortTopicName();
            
            DiscussionReplyController.UserReplys userReplysClass = userTopicClass.getReplys().get(0);
            userReplysClass.getIsMessageAuthor();
            userReplysClass.getQtAuthor();
            userReplysClass.getQuote();
            userReplysClass.getQtdate();
            userReplysClass.getExistqt();
            userReplysClass.getUser();
            userReplysClass.getUserShortName();
            userReplysClass.getMessage();
            userReplysClass.getPicture();
            userReplysClass.getStrdate();
            
            //Save Methods
            dis.saveReply();
            DiscussionReplyController.replyMessage rplNew = new DiscussionReplyController.replyMessage();
            rplNew.Message = 'fdasfads';
            rplNew.ParentMessage = 'fdasfads';
            rplNew.MessageId = 'fdasfads';
            
            dis.saveNewTopicReply();            
            DiscussionReplyController.replyMessage rplget = dis.getQuoteReply();
            dis.saveQuoteReply();
            
            DiscussionMessage__c msg = [Select Id, Message__c from  DiscussionMessage__c Limit 1];
            
            rplNew.Message = msg.Message__c;
            rplNew.ParentMessage = msg.Id;
            rplNew.MessageId = msg.Id;
            
            DiscussionReplyController.replyMessage rplget2 = dis.getQuoteReply();
            dis.saveNewTopicReply();
            dis.saveQuoteReply();   
        }catch(Exception e){
            throw e;
        }
        
    }
}