trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.2/src/classes/TeamsWidgetRecentDiscussionController.cls
public class TeamsWidgetRecentDiscussionController {
/*
	Id teamspaceId;
	DiscussionForum__c forum;
	
	public TeamsWidgetRecentDiscussionController() {
		
		teamspaceId = System.currentPageReference().getParameters().get('id');
		
		List<DiscussionForum__c> temp = [SELECT Id
				 				  		 FROM DiscussionForum__c
				 				  		 WHERE Team__c =: teamspaceId];
				   
				   
	    if(temp.size() > 0) {
	    	forum = temp[0];
	    }
	}
	
	public Id getTeamspaceId() {
		return teamspaceId;
	}
	
	public List<DiscussionTopic__c> getRecentDiscussions() {
		
		if(forum == null) return new List<DiscussionTopic__c>();
		
		List<DiscussionTopic__c> threads = [SELECT Subject__c
											 FROM DiscussionTopic__c
											 WHERE DiscussionForum__c =: forum.Id
											 ORDER BY LastPostDate__c DESC
											 LIMIT 5];
		
		return threads;
	}
*/
}