trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/classes/TeamsWidgetActiveDiscussionsController.cls
public with sharing class TeamsWidgetActiveDiscussionsController {
	
		public Boolean sidebar = false;
		
		/**
		*@void
		*/
		public void setSidebar(Boolean b){
	 		sidebar = b;
		}

		/**
		*@return Boolean
		*/
		public Boolean getSidebar(){
			return sidebar;
		}
		
		String teamId;
		
		// Setter method for Team Id variable
		public void setTeamId(String id) {
			teamId = id;
			genPermissions();			
		}
		
		// Get Team Id Attribute
		public String getTeamId(){
			return teamId;
		}

		Integer actdisSize;
		String userId = UserInfo.getUserId();
		
		public TeamsWidgetActiveDiscussionsController() {
			
		}

		/* ---------------------------- */
	   	/*   	 SHARING RULES			*/
	   	/* ---------------------------- */	
		public UserPermissions userPermissions = TeamsDetailController.userPermission.clone();
		
		public void genPermissions () {
			userPermissions.setId(UserInfo.getUserId());
			userPermissions.setTeam(teamId);
			userPermissions.setObjectType('Discussion');
			userPermissions.setPermissions();					
		}
		
		public UserPermissions getUserPermissions () {
			return userPermissions;
		}
	
		/* ---------------------------- */	
		
		List<DiscussionTopic__c> discussions = new List<DiscussionTopic__c>();
		
		public void refresh(){
			discussions = [ SELECT ViewCount__c, 
								   Subject__c, 
								   OwnerId, 
								   Name, 
								   MessageCount__c, 
								   PostedDate__c, 
								   PostedBy__r.Name,
								   LastPostedMessage__r.PostedDate__c,
								   LastPostedMessage__r.PostedBy__r.Name
							FROM DiscussionTopic__c d
							WHERE Team__c =: teamId
							ORDER BY d.CreatedDate desc LIMIT 4
							];
			
			actdisSize = discussions.size();
		}
		
	
		public List<Discussion> getDiscussions(){
			discussions = [ SELECT ViewCount__c, 
								   Subject__c, 
								   OwnerId, 
								   Name, 
								   MessageCount__c, 
								   PostedDate__c, 
								   PostedBy__r.Name,
								   LastPostedMessage__r.PostedDate__c,
								   LastPostedMessage__r.PostedBy__r.Name
							FROM DiscussionTopic__c d
							WHERE Team__c =: teamId
							ORDER BY d.CreatedDate desc LIMIT 4
							];
			
			actdisSize = discussions.size();
											
			List<Discussion> retDisc = new List<Discussion>();
			if(discussions.size() > 0) {
				for(DiscussionTopic__c d: discussions) {
					Discussion di = new Discussion(d);
					retDisc.add(di);					
				}
			}
			return retDisc;
		}
		
		public Integer getActiveDiscussionsSize(){
			return discussions.size();
		}
		
		public class Discussion{
			DiscussionTopic__c discussion;
			String author;
			Id authorId;
			String authorPicture;
			String lastReply;
			Integer views;
			Integer replies;
			Id replierId;
			String replierName;
			String lastPostDate;
			
			public Discussion(DiscussionTopic__c dis){
				discussion = dis;
				Datetime aux;
				views = dis.ViewCount__c.intValue();
				replies = dis.MessageCount__c.intValue();
				authorId = dis.PostedBy__c;
				author = dis.PostedBy__r.Name;

				if(discussion.LastPostedMessage__r.PostedBy__c == null){
						lastReply += '';
						authorPicture = '';
				}else {
					aux = discussion.LastPostedMessage__r.PostedDate__c;
					lastPostDate = formatDateToText(aux) + ' at ' + aux.format('hh:mm a');
					replierId = discussion.LastPostedMessage__r.PostedBy__c;
					replierName = discussion.LastPostedMessage__r.PostedBy__r.Name;
				}					
			}
			
			public DiscussionTopic__c getDiscussion(){
				return discussion;
			}
			
			public String getAuthor(){
				return author;
			}
			
			public Id getAuthorId(){
				return authorId;	
			}
			
			public String getLastPostDate(){
				return lastPostDate;
			}
						
			public String getLastReply(){
				return lastReply;
			}
			
			public Id getLastReplyAuthorId(){
				return replierId;
			}
			
			public String getLastReplyAuthor(){
				return replierName;
			}
			
			public String getAuthorPicture(){
				return authorPicture;
			}
			
			public Integer getViews(){
				return views;
			}
			
			public Integer getReplies(){
				return replies;
			}
			
			public String formatDateToText(Datetime d){
				DateTime now = System.now();
				String res = '';
				
				if(d.day() == now.day()){
					res = 'Today ';
				}else if(d.day() == (now.day() - 1)){
					res = 'Yesterday';
				}else{
					res = d.format('EEEE');
				}
				return res;
			}
			
		}

}