trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.5/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.1/src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.1/src/classes/WikiNewPageWidgetController.cls
public class WikiNewPageWidgetController {
	public String idTeam = System.currentPageReference().getParameters().get('id');
	public String idWikiPage = System.currentPageReference().getParameters().get('idWP');
	public String idTeamOverview = System.currentPageReference().getParameters().get('tid');
	
	public WikiNewPageWidgetController () {
		if (idTeamOverview != null && idTeamOverview != '') {
			idTeam = idTeamOverview;
		}
		
		if (idWikiPage != '' && idWikiPage != null) {
			idTeam = [SELECT Team__r.Id From WikiPage__c WHERE id =:idWikiPage].Team__r.Id;
		}
	}
	
	public String getIdTeam () {
		return idTeam;
	}
	
	public String getIdTeamOverview () {
		return idTeamOverview;
	}
	
	public String getIdWikiPage () {
		return idWikiPage;	
	}
	
	public void refreshWikis () {
		System.debug('\n //////////////////// \n \n Refresh!!! \n /////////////// \n');
	}
		
}