trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.5/src/classes/DiscussionWidgetNewDiscussionsController.cls
public class DiscussionWidgetNewDiscussionsController {


	public class Topics {
		String id;
 		String subject;
	
		public String getId () {
        	return id;
        }  
        
        public String getSubject () {
        	return subject;
        }  
              
        public void setSubject(String subject) {
        	Integer subjectLength; 

        	if(subject != null && subject != '' ){
        		subjectLength = subject.length();
        		if(subjectLength > 20) {
        			this.subject = subject.substring(0, 19) + '...' ;
        		}
        		else {
        			this.subject = subject;
        		}
        	}
        	else {
        		this.subject = null;
        	} 	
        } 
     
        
        public void setId (String Id) {
        	this.id = Id;
        }
	}
	
	List<Topics> topicsRes = new List<Topics>();
	
	public DiscussionWidgetNewDiscussionsController () {
		List<DiscussionTopic__c> newDiscussionTopics = new List<DiscussionTopic__c>();
		
		newDiscussionTopics = [SELECT Subject__c, Id
			   			  FROM DiscussionTopic__c
			   			  ORDER BY PostedDate__c DESC
			              LIMIT 5];	
			              
		
		
		for(DiscussionTopic__c item : newDiscussionTopics){
				
			Topics myTopic = new Topics();
			myTopic.setId(item.Id);	
			myTopic.setSubject(item.Subject__c);
			topicsRes.add(myTopic);
				 		
		}
	}
	
	public List<Topics> getNewDiscussionTopics() {
		return topicsRes;
	}
	
	public Boolean getTopicListCount() {	
		return (topicsRes.size() == 0);
	}
}