trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MiniFeed__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EducationHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmploymentHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UserCompetencies__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamspaceMember__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DiscussionThread__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcement__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProjectTask__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlogEntry__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WikiPage__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookmark__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamNew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEdit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamDelete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberLeave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberAdd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberJoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditRole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCreateNewType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminEditType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminNewTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleAddNewUser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeoplePhoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEducationChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEmploymentChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleCompetencyChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleChangeStatus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DiscussionNewReply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WikiNewPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WikiEditPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TaskAssigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TaskEdited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MiniFeed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mini Feed</label>
    <nameField>
        <label>Mini Feed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mini Feeds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamSubscription__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionNewReply__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DiscussionNewReply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscussionNewTopic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DiscussionNewTopic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscussionReplyToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DiscussionReplyToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignToMeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignToMeChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignedToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignedToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamMemberJoinLeave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TeamMemberJoinLeave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamMemberStatusUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TeamMemberStatusUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>TeamSuscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamSuscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiCreatedByMeUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiCreatedByMeUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WikiNewPage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiNewPage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WikiPageUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiPageUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>TeamSubscription</label>
    <nameField>
        <label>TeamSubscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamSubscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TeamsSubscribersEmailServicesTest.cls
public class TeamsSubscribersEmailServicesTest {
    
    public static Boolean alreadyRun = false;
    
    public static testMethod void test(){
    	
    	if(!alreadyRun){
    		alreadyRun = true;
	    	GenerateEnvironmentTest.gen();
	    	Test.startTest();
	    	
	    	TeamsSubscribersEmailServices emailService = new TeamsSubscribersEmailServices();	
	    	
	    	Team__c team = [select Id, (select User__c from TeamMembers__r where User__c !=: UserInfo.getUserId()) from Team__c limit 1];
	    	
	    	TeamSubscription__c subscription = new TeamSubscription__c();
			subscription.WikiPageUpdated__c = true; 
			subscription.WikiNewPage__c = true; 
			subscription.WikiCreatedByMeUpdated__c = true; 
			subscription.TeamMemberStatusUpdated__c = true; 
			subscription.TeamMemberJoinLeave__c = true; 
			subscription.ProjectTaskDeleted__c = true; 
			subscription.ProjectTaskChanged__c = true; 
			subscription.ProjectTaskAssignedToMe__c = true; 
			subscription.ProjectTaskAssignToMeChanged__c = true;
			subscription.DiscussionReplyToMe__c = true; 
			subscription.DiscussionNewTopic__c = true; 
			subscription.DiscussionNewReply__c = true;
	    	subscription.Team__c = team.Id;
			subscription.User__c = team.TeamMembers__r[0].User__c;
			insert subscription;
			
	    	MiniFeed__c feed = new MiniFeed__c();
	    	feed.Name = 'Some name';
	    	feed.Message__c = 'Some Message';
	    	
	    	feed.Type__c = 'TeamMemberJoin';
	    	feed.User__c = team.TeamMembers__r[0].User__c;
	    	insert feed;
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');
	    	
	    	emailService.setIsTest(true);
	    	
	    	emailService.mf.Type__c = 'TeamMemberLeave';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');    	
	    	
	    	emailService.mf.Type__c = 'DiscussionNewTopic';
	    	DiscussionTopic__c auxTopic = [select id from DiscussionTopic__c order by createdDate desc limit 1];
	    	emailService.mf.Message__c = 'created new discussion topic <a href="/apex/DiscussionDetail?id=' + auxTopic.Id + '"/>Topic</a>';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');    	
	    	
	    	emailService.mf.Type__c = 'DiscussionNewReply';
	    	DiscussionMessage__c auxMessage = [select id from DiscussionMessage__c order by createdDate desc limit 1];
	    	emailService.mf.Message__c = '<span style="display:none;">' + auxMessage.Id + '</span>';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');     	
	    	
	    	
	    	ProjectTask__c auxTask = [select id from ProjectTask__c order by createdDate desc limit 1];
	    	emailService.mf.Type__c = 'TaskAssigned';
	    	emailService.mf.Message__c = '<span style="display:none;">' + auxTask.Id + '</span>';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');
	    	
	    	emailService.setIsTaskEdit(true);
	    	
	    	emailService.mf.Type__c = 'TaskAssignedDelete';
	    	emailService.mf.Message__c = '<span style="display:none;">' + auxTask.Id + '</span>';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');    	
	    	
	    	emailService.mf.Type__c = 'TaskEdited';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');
	
	    	emailService.mf.Type__c = 'TaskDelete';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');
	    	
	    	WikiPage__c wiki = [select Id from WikiPage__c limit 1];
	    	emailService.mf.Type__c = 'WikiEditPage';
	    	emailService.mf.Message__c = '<a href="/apex/WikiPage?idWP=' + wiki.Id + '">Link</a>';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');    	
	    	
	    	emailService.mf.Type__c = 'WikiNewPage';
	    	emailService.TeamsMembersSubscribers(team.Id, feed, 'Some string');     	
	    	
	    	emailService.mf.Type__c = 'PeopleChangeStatus';
	    	emailService.TeamsMembersSubscribers(null, feed, 'Some string');   
	    	
	    	Test.stopTest(); 
    	}	
    }	
}