trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/main/src/classes/TeamsMyTeamsWidgetTest.cls
@IsTest private class TeamsMyTeamsWidgetTest {
	public static testMethod void testTeam() {
  		try{
  			TeamsMyTeamsWidgetController team = new TeamsMyTeamsWidgetController();
  			team.getOwnTeams();
  			TeamsMyTeamsWidgetController.Teams teams = new TeamsMyTeamsWidgetController.Teams(new TeamMember__c());
  			String sortBy = team.getSortBy();
  			String p = teams.getPicture();
  			Boolean sortDesc = team.getSortByDesc();
  			TeamMember__c member = teams.getTeamMember();
  			
  			team.setSortBy('Team__r.Name');
  			team.sortList();

  			team.setSortBy('TeamProfile__r.Name');
  			team.sortList();

  			team.setSortBy('Team__r.Name');
  			team.sortList();  			

  			team.setSortBy('TeamProfile__r.Name');
  			team.sortList(); 
  			
  			team.getNamespace();
	
  		}catch(Exception e){
  			throw e;
  		}
   	}
}