trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.1/src/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

branches/0.1/src/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.5/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.6/src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.5/src/classes/UserPermissionsTest.cls
@IsTest private class UserPermissionsTest {
    
    /**
    * Run code coverage for UserPermissions class
    *@static
    *@void
    *@testMethod
    */ 
    public static testMethod void UserPermissionsTest(){
		GenerateEnvironmentTest.gen();
		
		Test.startTest();
		
		System.debug('\n\n///////////////////////////////////////\n INTO TEST  \n//////////////////////////////////\n\n');
		
        List<User> NOTteamAdmin = [Select id, Profile.PermissionsModifyAllData, ProfileId, Name From User where Profile.Name = 'Read Only' limit 1];
        //Set non Admin user
        String userId;
        if (NOTteamAdmin.size() > 0) {
            userId = NOTteamAdmin[0].Id;
        }
        else {
            userId = UserInfo.getUserId();
        }

		UserPermissions up = new UserPermissions();
           	
       	System.debug('\n\n///////////////////////////////////////\n USER ID: ' + userId + '\n//////////////////////////////////\n\n');
        up.setId(userId);
        
        //Get one TeamMember & Team for non Admin user.
        List<Team__c> teamList = new List<Team__c>();
        teamList = [SELECT id FROM Team__c];
        if (teamList.size() > 0 ) {
            TeamMember__c teamMember = [select Id, Team__c from TeamMember__c where User__c !=: userId limit 1];
    		
            //Test Team Permissions
            up.setTeam(teamMember.Team__c);
            up.setObjectType('Team');
            up.setPermissions();
            
            //Test WikiPage Permissions
            WikiPage__c wp = [select Id from WikiPage__c limit 1];
            up.setObjectType('Wiki');
            up.setPermissions();
            
            
            //Test DiscussionForum Permissions
            DiscussionForum__c df = [select Id from DiscussionForum__c limit 1];
            up.setObjectType('DiscussionForum');
            up.setPermissions();
            
            //Test DiscussionMessage Permissions
            DiscussionMessage__c dm = [select Id from DiscussionMessage__c limit 1];
            up.setObjectType('DiscussionMessage');
            up.setPermissions();
            
            //Test DiscussionTopic Permissions
            DiscussionTopic__c dt = [select Id from DiscussionTopic__c limit 1];
            up.setObjectType('DiscussionTopic');
            up.setPermissions();        
    
            //Test ProjectTask Permissions
            ProjectTask__c pt = [select Id from ProjectTask__c limit 1];
            up.setObjectType('Project');
            up.setPermissions();
            
            //Test getters
            userId = up.getId();        
            String objectType = up.getObjectType();
            String teamId = up.getTeam();
            // String tId = up.getObjectId();       
            Boolean canMange = up.getCanManage();
            Boolean canCreate = up.getCanCreate();
            Boolean canComment = up.getCanComment();
            Boolean canView = up.getCanView();
        }
        
        //Test Admin User (current user should be App Admin for this)
        up = new UserPermissions();
        up.setId(UserInfo.getUserId());
        up.setPermissions(); 
       	
       	Test.stopTest();
    }
    
}