trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/FavoriteWikis__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Favorite Wikis</relationshipLabel>
        <relationshipName>FavoriteWikis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FavoriteWikis1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>WikiPage</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Favorite Wikis</relationshipLabel>
        <relationshipName>FavoriteWikis</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Wikis</label>
    <nameField>
        <label>FavoriteWikis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Favorite Wikis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/WikiWidgetMyFavoritesController.cls
/**
*@author Gabriel Rilo @ 18/12/2008
*/
public class WikiWidgetMyFavoritesController {
	
	
	/**
	* Costructor
	*/
	public WikiWidgetMyFavoritesController () {

	}
	
 	
   	
	/**
	*@return List<FavoriteWikis__c> 
	*/
   	public List<FavoriteWikis__c> getFavorite () {
   		return	[SELECT WikiPage__r.Team__r.Id, WikiPage__r.Team__r.Name, WikiPage__r.Name, WikiPage__r.Id FROM FavoriteWikis__c WHERE User__c = :UserInfo.getUserId() order by WikiPage__r.Name LIMIT 5];
   	}    	
   	
   	/**
   	*@return Integer
   	*/
   	public Integer getCntFav () {
   		return [select count() from FavoriteWikis__c where User__c = :UserInfo.getUserId()];
   	} 
  	

}