trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/MiniFeed__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Mini Feeds</relationshipLabel>
        <type>Lookup</type>
    </fields>
    <label>Mini Feed</label>
    <nameField>
        <label>Mini Feed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mini Feeds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <label>ContactEmail</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Id2__c</fullName>
        <description>This field copies the Id of the instance and stores it as a string. We had to do this so that we can compare Id&apos;s in sosl statements w/o having to turn on the private apis.
Aug 2008 -Marcos</description>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewMemberProfile__c</fullName>
        <label>NewMemberProfile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentTeam__c</fullName>
        <label>Parent Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>ParentTeam</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublicProfile__c</fullName>
        <label>PublicProfile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipName>Teams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TeamCreatedBy__c</fullName>
        <label>TeamCreatedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TeamCreatedDate__c</fullName>
        <label>TeamCreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TeamType__c</fullName>
        <label>Team Type</label>
        <referenceTo>TeamType__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/TeamType__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Team Type</label>
    <nameField>
        <label>TeamType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/classes/ValidateTeamSharingControllerTest.cls
@IsTest private class ValidateTeamSharingControllerTest {
	public static testMethod void testValidateTeamSharing() {

		GenerateEnvironmentTest.gen();
        Test.startTest();  
		GenerateEnvironmentTest.createTeamType();
		Team__c newTeam = GenerateEnvironmentTest.newTeam; 
		
		ValidateTeamSharingController validate = new ValidateTeamSharingController();
		
		/* ONE TEAM 1 */
		validate.setLastTeamId();
		validate.setTotalRemainingTeams();
		
		/* Change the owner, so i can delete the team Queue */
		newTeam.OwnerId = UserInfo.getUserId();
		
		String teamId;
		teamId = newTeam.Id;
		
		/**** 
		//////////////////////
		Delete the team associates Objects to do the validations failds
		/////////////////////
		****/
		/* Delete the Team share */
		List<Team__Share> newTeamShare = [select id from Team__Share where ParentId=: teamId and RowCause = 'Manual'];
		delete newTeamShare;
		
		/* Delete Mini Feeds */
		List<MiniFeed__c> newTeamMiniFeeds = [select id from MiniFeed__c where team__c =: teamId];
		List<MiniFeed__Share> newTeamMiniFeedsShare = [select id from MiniFeed__Share where ParentId in:newTeamMiniFeeds and RowCause = 'Manual'];
		delete newTeamMiniFeedsShare;
	
		/* Delete the Members */
		List<TeamMember__c> newTeamMembers = [select id from TeamMember__c where Team__c =: teamId];
		List<TeamMember__Share> newTeamMembersShare = [select id from TeamMember__Share where ParentId in:newTeamMembers and RowCause = 'Manual'];
		delete newTeamMembersShare;
		
		/* Delete the Projects */
		List<Project2__c> newTeamProjects = [select id from Project2__c where Team__c =: teamId];
		List<Project2__Share> newTeamProjectsShare = [select id from Project2__Share where ParentId in:newTeamProjects and RowCause = 'Manual'];
		delete newTeamProjectsShare;
		
		
		/* Delete the DiscussionForums */
		List<DiscussionForum__c> newTeamDiscussionForums = [select id from DiscussionForum__c where Team__c =: teamId];
		List<DiscussionForum__Share> newTeamDiscussionForumsShare = [select id from DiscussionForum__Share where ParentId in:newTeamDiscussionForums and RowCause = 'Manual'];
		delete newTeamDiscussionForumsShare;
		
		/* Delete the Queues */
		List<Group> newTeamQueues = [select id, Name from Group where name like :('%' + teamId + '%') and name !=: ('teamSharing' + teamId) and name !=: ('Team' + teamId)];
		List<GroupMember> iterQueueMembers = [select id from GroupMember where GroupId in: newTeamQueues];
		delete iterQueueMembers;
		
		List<Group> teamSharingGroup = [select id, Name from Group where name =: ('teamSharing' + teamId)];
		List<GroupMember> teamSharingGroupMembers = [select id from GroupMember where GroupId =: teamSharingGroup[0].Id];
		delete teamSharingGroupMembers;
		 
		
		validate.setTeamParam(teamId);
		String teamParam = validate.getTeamParam();
		try {
			validate.startValidation();
		}catch (Exception e) {
			System.assert(true, e);
		}
		
		validate.getProgressPercent();
		validate.getRemainingTeams();
		validate.getTotalTeams();
		validate.getDebugging();
		
		if (validate.getProcessing()) {
			validate.processValidation();
		}
		
		validate.getProgressPercent();
		validate.getResults();
		
		Test.stopTest();
	}
	
	public static testMethod void testValidateTeamSharing2() {
		GenerateEnvironmentTest.gen();
		Test.startTest();
		ValidateTeamSharingController validate = new ValidateTeamSharingController();
		
		/* ONE TEAM 2 */
		validate.setLastTeamId();
		validate.setTotalRemainingTeams();
		
		/* Create the team to process */
		Team__c newTeam = [Select t.TeamType__c, t.TeamCreatedDate__c, t.TeamCreatedBy__c, t.SystemModstamp, t.PublicProfile__c, t.Picture__c, t.ParentTeam__c, t.OwnerId, t.NewMemberProfile__c, t.Name, t.LastModifiedDate, t.LastModifiedById, t.IsDeleted, t.Id2__c, t.Id, t.Description__c, t.CreatedDate, t.CreatedById, t.ContactEmail__c From Team__c t order by CreatedDate desc limit 1];
		
		Team__c newTeam2 = new Team__c();
		newTeam2 = newTeam;
		
		/* Change the owner, so i can delete the team Queue */
		newTeam2.OwnerId = UserInfo.getUserId();
		
		String teamId = newTeam.Id;
		
		/**** 
		//////////////////////
		Delete the team associates Objects to do the validations failds
		/////////////////////
		****/
		/* Delete the Team share */
		List<Team__Share> newTeamShare = [select id from Team__Share where ParentId=: teamId and RowCause = 'Manual'];
		
		/* Delete Mini Feeds */
		List<MiniFeed__c> newTeamMiniFeeds = [select id from MiniFeed__c where team__c =: teamId];
		
		/* Delete the Members */
		List<TeamMember__c> newTeamMembers = [select id from TeamMember__c where Team__c =: teamId];
		
		/* Delete the Projects */
		List<Project2__c> newTeamProjects = [select id from Project2__c where Team__c =: teamId];
		
		
		/* Delete the DiscussionForums */
		List<DiscussionForum__c> newTeamDiscussionForums = [select id from DiscussionForum__c where Team__c =: teamId];
		
		/* Delete the Queues */
		List<Group> newTeamQueues = [select id, Name from Group where name like :('%' + teamId + '%') and name !=: ('teamSharing' + teamId) and name !=: ('Team' + teamId)];
		
		/* Delete the Team share */
		delete newTeamShare;
		
		/* Delete Mini Feeds */
		delete newTeamMiniFeeds;
	
		/* Delete the Members */
		delete newTeamMembers;
		
		/* Delete the Projects */
		delete newTeamProjects;
		
		/* Delete the DiscussionForums */
		delete newTeamDiscussionForums;
		
		/* Delete the Queues */
		validate.setTeamParam(teamId);
		validate.startValidation();
		validate.getProgressPercent();
		validate.getRemainingTeams();
		validate.getTotalTeams();
		validate.getDebugging();
		
		if (validate.getProcessing()) 
			validate.processValidation();
		
		Test.stopTest();
	}	
}