trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>LastViewedDate__c</fullName>
        <label>LastViewedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TeamsWidgetPopularDiscussionsController.cls
public class TeamsWidgetPopularDiscussionsController {
	
	Integer popdisSize;
	
	//Constructor
	public TeamsWidgetPopularDiscussionsController()
	{
		getDiscussions();
	}
	
	//getDiscussions
	public List<DiscussionTopic__c> getDiscussions(){ 
			
		    List<DiscussionTopic__c> discussions = new List<DiscussionTopic__c>();
			//QUERY BASED ON DiscussionWidgetMostReadController
			discussions =   [select Id, 
							Subject__c, 
							LastViewedDate__c 
							from DiscussionTopic__c 
							order by LastViewedDate__c 
							desc limit 5];
			
			popdisSize = discussions.size();
			
			return discussions;
	}	
	
	public Integer getPopularDiscussionsSize(){
		return popdisSize;
	}
	
}