trunk/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.1/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

0.1/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamRelationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateDiscussionTopics__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateDiscussionTopics</label>
        <type>Checkbox</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.1/src/classes/TeamsWidgetActiveDiscussionsController.cls
public with sharing class TeamsWidgetActiveDiscussionsController {
	
		String teamId = null;
		
		// Setter method for Team Id variable
		public void setTeamId(String id) {
			teamId = id;			
		}
		
		// Get Team Id Attribute
		public String getTeamId(){
			return teamId;
		}

		Integer actdisSize;
		
		String userId = UserInfo.getUserId();

		public Boolean getnewPrivileges() {
			
			Boolean result = true;
			
	    	List<TeamMember__c> tm = new List<TeamMember__c>();	
	    	
		    tm  = [Select 
					t.User__c, 
					t.Team__c, 
					t.TeamProfile__r.CreateDiscussionTopics__c, 
					t.TeamProfile__c From TeamMember__c t 
					where t.Team__c =: teamId and t.User__c =: userId ];
			
			if(tm.size() > 0){
				if(tm[0].TeamProfile__c != null){
					result = tm[0].TeamProfile__r.CreateDiscussionTopics__c;
				}							
			}
			else {
				result = false;					
			}
			return result;
	    }
		
		
		public List<Discussion> getDiscussions(){
			
		    List<DiscussionTopic__c> discussions = new List<DiscussionTopic__c>();

			discussions = [ SELECT ViewCount__c, 
								   Subject__c, 
								   OwnerId, 
								   Name, 
								   MessageCount__c, 
								   PostedDate__c, 
								   PostedBy__r.Name,
								   LastPostedMessage__r.PostedDate__c,
								   LastPostedMessage__r.PostedBy__r.Name
							FROM DiscussionTopic__c d
							WHERE Team__c =: teamId
							ORDER BY d.CreatedDate desc LIMIT 4
							];
			
			actdisSize = discussions.size();
											
			List<Discussion> retDisc = new List<Discussion>();
			
			if(discussions.size() > 0) {
				
				for(DiscussionTopic__c d: discussions) {
					Discussion di = new Discussion(d);
					retDisc.add(di);					
				}
				
			}
			return retDisc;
		}
		
		public Integer getActiveDiscussionsSize(){
			return actdisSize; 
		}
		
		public class Discussion{
			DiscussionTopic__c discussion;
			String author;
			Id authorId;
			String authorPicture;
			String lastReply;
			Integer views;
			Integer replies;
			Id replierId;
			String replierName;
			String lastPostDate;
			
			public Discussion(DiscussionTopic__c dis){
				
				discussion = dis;
				
				Datetime aux;
				views = dis.ViewCount__c.intValue();
				replies = dis.MessageCount__c.intValue();
				authorId = dis.PostedBy__c;
				author = dis.PostedBy__r.Name;

				if(discussion.LastPostedMessage__r.PostedBy__c == null){
						lastReply += '';
						authorPicture = '';
				}
				else {
					aux = discussion.LastPostedMessage__r.PostedDate__c;
												
					lastPostDate = formatDateToText(aux) + ' at ' + aux.format('hh:mm a');
						
					replierId = discussion.LastPostedMessage__r.PostedBy__c;

					replierName = discussion.LastPostedMessage__r.PostedBy__r.Name;
				}					

			}
			
			public DiscussionTopic__c getDiscussion(){
				return discussion;
			}
			
			public String getAuthor(){
				return author;
			}
			
			public Id getAuthorId(){
				return authorId;	
			}
			
			public String getLastPostDate(){
				return lastPostDate;
			}
						
			public String getLastReply(){
				return lastReply;
			}
			
			public Id getLastReplyAuthorId(){
				return replierId;
			}
			
			public String getLastReplyAuthor(){
				return replierName;
			}
			
			public String getAuthorPicture(){
				return authorPicture;
			}
			
			public Integer getViews(){
				return views;
			}
			
			public Integer getReplies(){
				return replies;
			}
			
			public String formatDateToText(Datetime d){
				DateTime now = System.now();
				String res = '';
				
				if(d.day() == now.day()){
					res = 'Today ';
				}else if(d.day() == (now.day() - 1)){
					res = 'Yesterday';
				}else{
					res = d.format('EEEE');
				}
				return res;
			}
			
		}

}