trunk/objects/MiniFeed__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EducationHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmploymentHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UserCompetencies__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamspaceMember__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DiscussionThread__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcement__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProjectTask__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlogEntry__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WikiPage__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookmark__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamNew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEdit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamDelete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberLeave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberAdd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberJoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditRole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCreateNewType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminEditType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminNewTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleAddNewUser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeoplePhoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEducationChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEmploymentChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleCompetencyChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleChangeStatus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MiniFeed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mini Feed</label>
    <nameField>
        <label>Mini Feed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mini Feeds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.6/src/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/src/objects/PeopleSubscription__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>People Subscription</label>
    <nameField>
        <label>People Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.5/src/classes/PeopleOverviewTest.cls
@IsTest private class PeopleOverviewTest { 
    public static testMethod void testPeople() {
        try{        
			GenerateEnvironmentPeopleTest.gen();
			Test.startTest();

            PeopleOverviewController overview = new PeopleOverviewController();
                
            String time = overview.getCurrentTime();
            PageReference page = overview.profileExist();
            
            List<PeopleProfile__c> profile = overview.getPeopleProfile();
            List<PeopleOverviewController.People> newFaces = overview.getNewFaces();
            List<PeopleOverviewController.CloudItems> clouds1 = overview.generateCloud('Employer');
            List<PeopleOverviewController.CloudItems> clouds2 = overview.generateCloud('School');
            List<PeopleOverviewController.CloudItems> clouds3 = overview.generateCloud('Competency');           
            List<PeopleOverviewController.CloudItems> competenciesCloud = overview.getCompetenciesCloud(); 
            List<PeopleOverviewController.CloudItems> formerCompaniesCloud = overview.getFormerCompaniesCloud();

            // PEOPLE inner class
            PeopleOverviewController.People peopleObject = new PeopleOverviewController.People();
            peopleObject.getUserId();
            peopleObject.getUsername();
            peopleObject.getDivision();
            peopleObject.getDepartment();
            peopleObject.getTitle();
            peopleObject.getImageId();
            
            
            // MINIFEED inner class
            PeopleOverviewController.minifeed minifeedObject = new PeopleOverviewController.minifeed();
            minifeedObject.getTypeOfFeed();
            minifeedObject.getName();
            minifeedObject.getUser();
            minifeedObject.getMessage();
            minifeedObject.getFeedDate();
            minifeedObject.getFeedDateString();
            minifeedObject.getFeedDateClass();
            
            // CLOUDITEMS inner class
            PeopleOverviewController.CloudItems cloudItemsObject = new PeopleOverviewController.CloudItems();
            cloudItemsObject.getName();
            cloudItemsObject.getLevel();
            cloudItemsObject.getCount();
            
            MiniFeed__c auxMiniFeed = new MiniFeed__c();
            auxMiniFeed.Message__c = 'is fooing';
            auxMiniFeed.Type__c = 'PeopleChangeStatus';
            auxMiniFeed.User__c = UserInfo.getUserId();
            insert auxMiniFeed;
            
            PeopleSubscription__c newPeopleSub = new PeopleSubscription__c();
            newPeopleSub.Subscriber__c = UserInfo.getUserId();
            newPeopleSub.Person__c = UserInfo.getUserId();	 
            insert newPeopleSub;
            
            List<PeopleOverviewController.miniFeed> feeds = overview.getMiniFeeds();
            String feedType = feeds[0].getTypeOfFeed();
            feeds[0].setTypeOfFeed('Some Type');
            feeds[0].setName('Some Name');
            String feedName = feeds[0].getName();
            String userName = feeds[0].getUser();
            feeds[0].setUser(UserInfo.getUserName());
            String message = feeds[0].getMessage();
            feeds[0].setMessage('Some Message');
            Datetime d = feeds[0].getFeedDate();
            feeds[0].setFeedDate(System.now());
            String dateStr = feeds[0].getFeedDateString();
            feeds[0].setFeedDateString(System.now().format('HH:mm:ss.SSS'));
            String dateClass = feeds[0].getFeedDateClass();
            feeds[0].setFeedDateClass(dateClass); 
            
			Test.stopTest();
        }catch(Exception e){
            throw e;
        }   
    }   
}