trunk/objects/PeopleProfile__c.object
<CustomObject>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/main/src/classes/TeamsOverviewTest.cls
@IsTest private class TeamsOverviewTest {

    public static testMethod void testTeam() {
        try{
            
            GenerateEnvironmentTest.gen();
            Test.startTest();
            
            TeamsOverviewController team = new TeamsOverviewController();
            team.setIsTest(true);
            List<PeopleProfile__c> profiles = team.getPeopleProfile();
            TeamsOverviewController.teams t = new TeamsOverviewController.teams();
            TeamsOverviewController.Letters l = new TeamsOverviewController.Letters(); 
            team.getPeopleProfile();
            team.profileExist();
            
            PaginatorControllerTest.PaginatorController();
            
            team.setFilter('newTeams');
            team.teamsForTabs();
            team.setLetterFilter();
            PageReference pr = team.profileExist();
            
            // GENERATED FOR CODE COVERAGE
            TeamUtil.isTest = true;
            Team__c teamCodCov = GenerateEnvironmentTest.newTeam;
            delete teamCodCov;

            TeamMember__c teamMemCodCov = GenerateEnvironmentTest.newTeamMember;
            update teamMemCodCov;

            TeamProfile__c teamProfCodCov = GenerateEnvironmentTest.newTeamProfile;
            update teamProfCodCov;
            TeamUtil.isTest = false;

            Test.stopTest();
        }catch(Exception e){
            throw e;
        }   
    
    }
    
}