trunk/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>AboutMe__c</fullName>
        <label>About Me</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Aol__c</fullName>
        <label>Aol</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delicious__c</fullName>
        <label>Delicious</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gtalk__c</fullName>
        <label>Gtalk</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePageUrl__c</fullName>
        <label>Home Page Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Linkedin__c</fullName>
        <label>Linkedin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skype__c</fullName>
        <label>Skype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YahooIM__c</fullName>
        <label>YahooIM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>changeHistoryDate__c</fullName>
        <label>changeHistoryDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>changeHistory__c</fullName>
        <label>changeHistory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/src/classes/PeopleSidebarControllerTest.cls
@IsTest private class PeopleSidebarControllerTest {
    public static testMethod void testProjectTaskDetailController() {
        try{
            PeopleSidebarProfileController sidebar = new PeopleSidebarProfileController();
            
            PeopleProfile__c newUserProfile = new PeopleProfile__c();
            List<PeopleProfile__c> userProfiles = [select id from PeopleProfile__c where User__c =:UserInfo.getUserId()];
            if(userProfiles.size() == 0) {
	            newUserProfile.User__c = UserInfo.getUserId();
	            newUserProfile.Name= 'foo';
				newUserProfile.YahooIM__c= 'foo';
				newUserProfile.Skype__c= 'foo';
				newUserProfile.HomePageUrl__c= 'foo';
				newUserProfile.Gtalk__c= 'foo';
				newUserProfile.Facebook__c= 'foo';
				newUserProfile.Delicious__c= 'foo';
				newUserProfile.Aol__c= 'foo';
				newUserProfile.AboutMe__c= 'foo';
				newUserProfile.Linkedin__c= 'foo';
				newUserProfile.changeHistory__c= 'foo';
				newUserProfile.changeHistoryDate__c = System.now();
	            upsert newUserProfile;
            }
            
            sidebar.getCurrentTime();
            sidebar.getShowStatus();
            
            
            List<PeopleProfile__c> profiles = sidebar.getPeopleProfile();
            String s1 = sidebar.getCurrentTime();
            String s2 = sidebar.getMyPicture();
            PeopleProfile__c profile = sidebar.getMySidebarProfile();
            sidebar.subscriptionCounts();
            Integer n1 = sidebar.getCountImSubscribedTo();
            Integer n2 = sidebar.getCountSubscribedToMe();
            Boolean b1 = sidebar.getShowSubscribedPeople();
            
            //STATUS inner class
            PeopleSidebarProfileController.Status status = new PeopleSidebarProfileController.Status();
            status = sidebar.getStatus();
            status.getMessage();
            status.setModified(System.now());
            
            Datetime myDate = datetime.newInstance(System.now().year(), System.now().month(), System.now().day(), System.now().hour(), System.now().minute() - 1, System.now().second());
            status.setModified(myDate);
            
            myDate = datetime.newInstance(System.now().year(), System.now().month(), System.now().day(), System.now().hour(), System.now().minute() - 2, System.now().second());
            status.setModified(myDate);
            
            myDate = datetime.newInstance(System.now().year(), System.now().month(), System.now().day(), System.now().hour() - 2, System.now().minute(), System.now().second());
            status.setModified(myDate);
            
            myDate = datetime.newInstance(System.now().year(), System.now().month(), System.now().day() - 2, System.now().hour(), System.now().minute(), System.now().second());
            status.setModified(myDate);
            
            myDate = datetime.newInstance(System.now().year(), System.now().month(), System.now().day() - 8, System.now().hour(), System.now().minute(), System.now().second());
            status.setModified(myDate);
            
            status.getModified();  
            
            sidebar.EditStatus();
            
        }catch(Exception e){
            throw e;
        }
    }
}