trunk/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>AboutMe__c</fullName>
        <label>About Me</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Aol__c</fullName>
        <label>Aol</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delicious__c</fullName>
        <label>Delicious</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gtalk__c</fullName>
        <label>Gtalk</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePageUrl__c</fullName>
        <label>Home Page Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Linkedin__c</fullName>
        <label>Linkedin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skype__c</fullName>
        <label>Skype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YahooIM__c</fullName>
        <label>YahooIM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>changeHistoryDate__c</fullName>
        <label>changeHistoryDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>changeHistory__c</fullName>
        <label>changeHistory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.6/src/classes/PeopleNewEditProfileTest.cls
@IsTest private class PeopleNewEditProfileTest {
    public static testMethod void testPeople() {
        try{
			GenerateEnvironmentPeopleTest.gen();
			Test.startTest();

            ApexPages.StandardController controller;
            PeopleNewEditProfileController people = new PeopleNewEditProfileController(controller);
            
            PeopleProfile__c newUserProfile = new PeopleProfile__c();
            List<PeopleProfile__c> userProfiles = [select id from PeopleProfile__c where User__c =:UserInfo.getUserId()];
            if(userProfiles.size() == 0) {
	            newUserProfile.User__c = UserInfo.getUserId();
	            newUserProfile.Name= 'foo';
				newUserProfile.YahooIM__c= 'foo';
				newUserProfile.Skype__c= 'foo';
				newUserProfile.HomePageUrl__c= 'foo';
				newUserProfile.Gtalk__c= 'foo';
				newUserProfile.Facebook__c= 'foo';
				newUserProfile.Delicious__c= 'foo';
				newUserProfile.Aol__c= 'foo';
				newUserProfile.AboutMe__c= 'foo';
				newUserProfile.Linkedin__c= 'foo';
				newUserProfile.changeHistory__c= 'foo';
				newUserProfile.changeHistoryDate__c = System.now();
	            upsert newUserProfile;
            }
            people.setParam(UserInfo.getUserId());
            people.getPeopleProfile();
            people.getPProfile();
            PeopleProfile__c peopleProfile = people.getMySidebarProfile();
            people.getStatus();
            people.getShowStatus(); 
            people.getMyPicture();
            people.getCurrentTime();
            people.findPeople();
            people.getPeopleSearchObj();
            people.getError();
            people.init();          
            people.savePeopleProfile();
            people.cancelProfile();
            people.getNewUser();
            people.forwardTo('/apex/teamsOverview');
            
            PeopleNewEditProfileController.PeopleSearch peopleSrch = new PeopleNewEditProfileController.PeopleSearch();
            peopleSrch.setKeyword('word');
            peopleSrch.getKeyword();
            
            PeopleNewEditProfileController.Status status= new PeopleNewEditProfileController.Status();
            DateTime now = System.now();
            status.setModified(now);
            status.setMessage('Some Message');
            status.getMessage();
            
			Test.stopTest();
        }catch(Exception e){
            throw e;
        }
    }
}