trunk/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/ProjectAssignee__c.object
<CustomObject>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <label>Project Task</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectAssignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Assignees</relationshipLabel>
        <relationshipName>Assignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectAssignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Project Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAssignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.6/src/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>TaskProject</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.2/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.6/src/classes/TeamsOverlayNewTaskController.cls
/**
*@author Martin Prado @ 06/24/2008
*/
public class TeamsOverlayNewTaskController {
	
    ProjectTask__c theNewTask = new ProjectTask__c();
   	
   	public String TEAMID = System.currentPageReference().getParameters().get('id'); 
   	public Project2__c currentProject = null;   
   	
    /**
    * Constructor
    */
    public TeamsOverlayNewTaskController(){
    	getCurrentProject();	
    	genPermissions();
	}

   	/**
   	*@param String team id
   	*/
   	public void setTEAMID (String teamId) {
   		this.TEAMID = teamId;
   	}
   	
    public ProjectTask__c newProyect = new ProjectTask__c();
   	/**
    *@return ProjectTask__c
    */
    public ProjectTask__c getTask(){
    	return newProyect;
    }
    
	/**
	*@param ProjectTask__c
	*/    
    public void setTask(ProjectTask__c value){
    	newProyect = value;
    }
    

    public TeamMember__c teamMember = new TeamMember__c();    
    /**
    *@return TeamMember__c
    */
    public TeamMember__c getTeamMember(){
    	return teamMember;
    }
    
    /**
    *@param TeamMember__c
    */
    public void setTeamMember(TeamMember__c value){
    	teamMember = value;
    }
    
   	/**
   	*@return String
   	*/
   	public String getCurrentTeamId(){
   		return TEAMID;
   	}
   	
    
    /**
    * Return members select options
    *@return List<SelectOption>
    */ 
	public List<SelectOption> getTeamMembers() {
    	List<TeamMember__c> teamMembers = new List<TeamMember__c>();  
  	 	List<SelectOption> options = new List<SelectOption>();
  	 	if(TEAMID != null){
	  	 	teamMembers = [Select t.Team__c, t.User__r.Name, t.Name, t.User__c, t.Id From TeamMember__c t where t.Team__c =: TEAMID];  
	  	 	options.add(new SelectOption('-1', 'Choose a team Member'));
	  	 	for(TeamMember__c c: teamMembers) {
	    		options.add(new SelectOption(c.User__c, c.User__r.Name)); 
	 		}
  	 	}
  	 	return options;
   	}

	/**
	* Read Project for current team
	*/
	public void getCurrentProject(){   
		if(TEAMID != null)
			currentProject = [select Id from Project2__c where Team__c =: TEAMID limit 1];
	}
	
	/**
	* Refresh method
	*/
	public void refreshMethod(){
		TeamsWidgetTasksMainController twtmc = new TeamsWidgetTasksMainController();
		twtmc.getAllProjectTasks();
	}
	
	/**
	* For rerender use
	*/
	public void dummyRefresh (){}   
	

	public UserPermissions userPermissions = TeamsDetailController.userPermission.clone();
	/**
	* Read user permissions
	*/	
	public void genPermissions () {
		userPermissions.setId(UserInfo.getUserId());
		userPermissions.setTeam(TEAMID);
		userPermissions.setObjectType('Project');
		userPermissions.setPermissions();		
	}
   	
   	/**
   	* Create new task
   	*@throws CustomException message Insufficient Privileges
   	*/
   	public void insertTask (){ 
   		if(!userPermissions.getCanCreate()){
        	throw new CustomException('Insufficient Privileges');
   		}else{	
   			newProyect.Milestone__c = false;
			newProyect.Team__c = TEAMID;
			newProyect.Project__c = currentProject.Id;
			newProyect.Priority__c = 'Normal';
			insert newProyect; 

	  		ProjectAssignee__c Assign = new ProjectAssignee__c();
			Assign.User__c = teamMember.User__c;
			Assign.ProjectTask__c = newProyect.Id;
			insert Assign;
			newProyect = new ProjectTask__c();
			Assign = new ProjectAssignee__c();
   		}
   	}
}