trunk/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/classes/ProjectTimelineController.cls
public class ProjectTimelineController {

    Team__c team = new Team__c();
    String param = System.currentPageReference().getParameters().get('id');
    
    public ProjectTimelineController(){
        getTeamAndProject(param);
    }
    
    /**
    * Get Team
    *@return Team__c
    */
    public Team__c getTeam(){
        return team;
    }
    
    /**
    * Get Project
    *@return Project2__c
    */
    public Project2__c getProject(){
        if(team.Projects__r.size() > 0)
        	return team.Projects__r[0];
        return new Project2__c();
    }
    
    /**
    * Get Team and Project for current team id
    *@void
    *@param String param
    */
    public void getTeamAndProject(String param){
        if(param != null){
            team = [select Id, Name, (Select Id, Name From Projects__r) from Team__c t where t.Id =: param];    
        }
    }
}