trunk/objects/ProjectAssignee__c.object
<CustomObject>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <label>Project Task</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectAssignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Assignees</relationshipLabel>
        <relationshipName>Assignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectAssignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Project Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAssignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.1/src/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Duration (Days)</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percent_Completed__c</fullName>
        <label>Percent Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

0.1/src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>25</length>
        <type>Text</type>
    </fields>

0.1/src/classes/TeamsWidgetMilestonesController.cls
public class TeamsWidgetMilestonesController {

	String teamId;
	
	// Setter method for Team Id variable
	public void setTeamId(String id) {
		teamId = id;		
	}
	// Getter Team Id variable
	public String getTeamId(){
		return teamId;
	}
	
			
	//Size of List
	Integer listSize = 0;
	public Integer getListSize (){
		return listSize;
	}
	
	public TeamsWidgetMilestonesController(){   
	}
	
	// New of List of milestones
	public List<ProjectTasks> getAllProjectTasks() {
	
	List<ProjectTask__c> milestones = new List<ProjectTask__c>();
	List<ProjectTasks> result = new List<ProjectTasks>();	
		milestones = [Select 		
	 					p.Name,
	 					p.Priority__c, 
	 					p.Id, 
	 					p.EndDate__c, 
	 					p.Duration__c, 
	 					p.Team__c,
	 					p.Milestone__c,
	 					p.Percent_Completed__c,
	 					p.Description__c, 
	 					(Select User__c, User__r.Name From ProjectAssignee__r) 
	 					From ProjectTask__c  p 
	 					where  p.Milestone__c = true 
	 					and p.Team__c =: teamId  
	 					order by p.EndDate__c asc limit 5
	 					];
	 					
	 	listSize = milestones.size();  // think there is a better way todo this
	 	
	 	// Retrieve Users
		Set<Id> users = new Set<Id>();		
	 	for( ProjectTask__c milestone : milestones) {
	 		if(milestone.ProjectAssignee__r.size() > 0){
				users.add(milestone.ProjectAssignee__r[0].User__c);
	 		}
	 	}
	 	
	 	Map<Id, User> userMap = new Map<Id,User>();
		for(User u: [SELECT Id, 
							Name, 
							(Select Name, Picture__c From People__r) 
							FROM User u 
							WHERE u.id IN: users]){
			userMap.put(u.Id, u);							
		}
	 				 
		for( ProjectTask__c milestone : milestones) {
			
			if(milestone.Percent_Completed__c < 100){
				
				ProjectTasks miMilestones = new ProjectTasks();
				miMilestones.setTaskName(milestone.Name);
				miMilestones.setTaskId(milestone.Id);
				if(milestone.ProjectAssignee__r.size() > 0){
					miMilestones.setUser(userMap.get(milestone.ProjectAssignee__r[0].User__c));					
				}
				miMilestones.setDaysCount(milestone.EndDate__c, milestone.Duration__c);
				miMilestones.setDayPercent(milestone.EndDate__c, milestone.Duration__c);
				miMilestones.setDayPercentRight(milestone.EndDate__c, milestone.Duration__c);
				miMilestones.setPriority(milestone.Priority__c);
				miMilestones.setEndDate(milestone.EndDate__c, milestone.Duration__c);
				miMilestones.setEndDateRight(milestone.EndDate__c, milestone.Duration__c);				
				miMilestones.setIsToLate(milestone.EndDate__c);  
				result.add(miMilestones);
			}
			
		 } 

		 return result;
	 }
		
					
	
	
	 public class ProjectTasks {
		
        public String TaskId;
        public String TaskName;
        public String DaysCount;
        public String UserId;
		public String UserName;
		public String EndDate;
		public String EndDateRight;
		public Integer DayPercent;
		public Integer DayPercentRight;
        public String Picture;
        public String Priority;
        public String isToLate;
      	DateTime now = System.now();
		
		
		public Integer getDayPercent() {
      		return DayPercent;
        }
        
        public void setDayPercent(Datetime endD, Double dur){
			
			Date miToday = Date.today();
			Date endDate = Date.newInstance(endD.year(), endD.month(),endD.day());
			Integer DayDiference = miToday.daysBetween(endDate);
			if(dur > 0){
				DayDiference = DayDiference -  dur.intValue();
			}  
           	if(DayDiference < 0)
           	{
        		DayPercent = 0;	
        	}
        	else 
        	{
        		 DayDiference = DayDiference * 4;
        		 if(DayDiference > 290)
        		 {
        		 	DayPercent = 290;
        		 }
        		 else 
        		 {
        		 	DayPercent = DayDiference;
        		 }
        	}
        }
        
        public Integer getDayPercentRight() {
      		return DayPercentRight;
        }
        
        public void setDayPercentRight(Datetime endD, Double dur){
			
			Date miToday = Date.today();
			Date endDate = Date.newInstance(endD.year(), endD.month(),endD.day());
			Integer DayDiference = miToday.daysBetween(endDate);
			if(dur > 0){
				DayDiference = DayDiference -  dur.intValue();
			}  
           	if(DayDiference < 0)
           	{
        		DayPercentRight = 0;	
        	}
        	else 
        	{
        		 DayDiference = DayDiference * 4;
        		 if(DayDiference > 131)
        		 {
        		 	DayPercentRight = 132;
        		 }
        		 else 
        		 {
        		 	DayPercentRight = DayDiference;
        		 }
        	}
        }
        
      	public ProjectTasks(){		
      	}
      	
      	public String getPicture() {
      		return Picture;
        }
      	
      	public String getEndDate() {
      		return EndDate;
        }
        
        public void setEndDate(Datetime endD, Double dif)
        {			
			if(dif > 0){
				endD = endD.addDays(-dif.intValue());
			}  
           	EndDate =  endD.format('MM/dd/yyyy');
        }
        
  		public String getIsToLate() {
      		return isToLate;
        }
        
         public void setEndDateRight(Datetime endD, Double dif)
        {
        	
			if(dif > 0){
				endD = endD.addDays(-dif.intValue());
			}  

           	 EndDateRight =  endD.format('(MM/dd)');
        }
        
  		public String getEndDateRight() {
      		return EndDateRight;
        }
        
        
        public void setIsToLate(Datetime endD){
        	
        	Date miToday = Date.today();
			Date myEndDate = Date.newInstance(endD.year(), endD.month(),endD.day());
			Integer DayDiference = miToday.daysBetween(myEndDate); 	
        	
        	if(DayDiference < 1){
        		isToLate = 'latter';	
        	}
            else {
            	isToLate = '';
            }
        }
        
        public String getDaysCount() {
      		return DaysCount;
        }
       
        public void setDaysCount(Datetime endD, Double dur){
        	
        	Date miToday = Date.today();
			Date endDate = Date.newInstance(endD.year(), endD.month(),endD.day());
			Integer DayDiference = miToday.daysBetween(endDate);   
			if(dur > 0){
				DayDiference = DayDiference -  dur.intValue();
			}   	
        	if(DayDiference < 2)
        	{	
        		if(DayDiference == 1 )
        		{
        			DaysCount = 'Tomorrow';
        		}
        		else if(DayDiference == 0 )
        		{
        			DaysCount = 'Today';
        		}
        		else 
        		{
        			
        			DaysCount =  (DayDiference*-1) +' days late';
        		}
        		
        	}
        	else 
        	{
        		 DaysCount = DayDiference +' days';
           	 	
        	}

        }
        
        public void setUser(User user){
        	
            UserName = user.name;
            UserId = user.Id;
        	
            if(user.People__r.size() > 0 &&
               user.People__r[0].Picture__c != null &&
               user.People__r[0].Picture__c != '') {
           		Picture = user.People__r[0].Picture__c;
            } else {
            	Picture = ' ';
            }
        }
        
        public String getUserId() {
      		return UserId;
        }
        
    	public String getUserName() {
       		return UserName;
        }
      	
      	public String getTaskId() {
            return TaskId;
        }
        public void setTaskId(String idTask){
            TaskId = idTask;
        }
        
      	public String getPriority() {
            return Priority;
        }
        
        public void setPriority(String pr){
            Priority = pr;
        }
        
        public String getTaskName() {
            return TaskName;
        }
        public void setTaskName(String sName){
            TaskName = sName;
        }
	 }
}