trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>ParentTask__c</fullName>
        <label>Parent Task</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ParentTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/classes/ProjectLookupController.cls
public class ProjectLookupController {
	//Constructor
	public ProjectLookupController(){}
	//Team ID
	public String teamID = System.currentPageReference().getParameters().get('id');
	public String taskID = System.currentPageReference().getParameters().get('taskId');
	public  List<ProjectTask__c> myTask = new List<ProjectTask__c>();
	
	public List<ProjectTask__c> getTask(){	
		if (taskID != null) {
			myTask = [Select p.ParentTask__c, p.Name, p.Id From ProjectTask__c p where p.Team__c =: teamID and p.Id !=: taskID];
		}else {
			myTask = [Select p.ParentTask__c, p.Name, p.Id From ProjectTask__c p where p.Team__c =: teamID];
		}
		
    	return myTask;
	}
}