trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/classes/TeamsOverlayNewTaskTest.cls
@IsTest private class TeamsOverlayNewTaskTest {
	 public static testMethod void TeamsOverlayNewTaskTest(){
	 	
	 	GenerateEnvironmentTest.gen();   
    	Test.startTest();
	 	TeamsOverlayNewTaskController con =  new TeamsOverlayNewTaskController();
	 	if(con.getTask() == null)
            System.assert(true, 'getTask Failed');  
        if(con.getTeamMember() == null)
            System.assert(true, 'getTeamMember Failed');  
        if(con.getCurrentTeamId() == null)
            System.assert(true, 'getCurrentTeamId Failed');  
        if(con.getTeamMembers() == null)
            System.assert(true, 'getTeamMembers Failed');  

        ProjectTask__c pT = new ProjectTask__c();
        pT.Name = 'Test Task';
        
        Team__c t = [select Id, Name from Team__c limit 1];
        TeamMember__c tM = [select id, Name, User__c, Team__c from TeamMember__c where team__c =: t.id limit 1];
       	con.setTEAMID(t.Id);
        con.getCurrentProject();
        con.genPermissions();
        
        con.setTask(pT);
        con.setTeamMember(tM);
		con.refreshMethod();
		con.dummyRefresh();
		con.getTeamMembers();
		con.insertTask();
		
		Test.stopTest();
	 }
}