trunk/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.3/src/classes/ProjectTimelineControllerTest.cls
@IsTest private class ProjectTimelineControllerTest {

    /**
    * Test for run code coverage for current class
    *@void
    *@static
    */
    public static testMethod void testTimelineController (){
        ProjectTimelineController pc = new ProjectTimelineController();
        Team__c t = [select Id, Name from Team__c limit 1];
        pc.getTeamAndProject(t.Id);
        t = pc.getTeam();
        Project2__c p = pc.getProject();    
    }
}