trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/TeamsWidgetTasksMainControllerTest.cls
@IsTest private class TeamsWidgetTasksMainControllerTest {
    public static testMethod void TeamsWidgetTasks() {
        
        GenerateEnvironmentTest.gen();
        Test.startTest();
        TeamsWidgetTasksMainController task = new TeamsWidgetTasksMainController();
        
        UserPermissions userPermissions = new UserPermissions();
        
       userPermissions = new UserPermissions();
        
        
        if (task.getUserPermissions() == null) {
            System.assert(true, 'Null Permissions');
        }
        
        userPermissions.getCanView();
        userPermissions.getCanComment();
        userPermissions.getCanManage();
        userPermissions.getCanCreate();
        userPermissions.getObjectType();
        userPermissions.getTeam();
        userPermissions.getId();
        
        task.setSidebar(true);
        if (task.getSidebar() == null) {
            System.assert(true,'getSidebar failed');
        }
		        
        /* ProjectTask class */
        TeamsWidgetTasksMainController.ProjectTask projectTaskClass = new TeamsWidgetTasksMainController.ProjectTask();
        projectTaskClass.getPicture();
        projectTaskClass.getEndDate();
        projectTaskClass.getIsToLate();
        projectTaskClass.getUserId();
        projectTaskClass.getUserName();
        projectTaskClass.getTaskId();
        projectTaskClass.getPriority();
        projectTaskClass.getPercent();
        projectTaskClass.getTaskName();
        
        ProjectTask__c pT = GenerateEnvironmentTest.newTask;
        Team__c team = GenerateEnvironmentTest.newTeam;
        task.setTeamId(team.Id);
        pT.Milestone__c = false;
        update pT;
        
        task.getProjectTaskbuild();
        task.getMyProjectTasks();
        task.getAllProjectTasks();  
        
        Test.stopTest();   
    }
}