trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Duration (Days)</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percent_Completed__c</fullName>
        <label>Percent Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/TeamsOverlayNewMilestoneTest.cls
@IsTest private class TeamsOverlayNewMilestoneTest {
	
	public static testMethod void TeamsOverlayNewMilestoneTest() {
		
		GenerateEnvironmentTest.gen();     
    	Test.startTest();
    	TeamsOverlayNewMilestoneController con = new TeamsOverlayNewMilestoneController();
    	con.setCurrentTeamId(GenerateEnvironmentTest.newTeam.Id);
    	if (con.getCurrentTeamId() == null) 
    		System.assert(true,'getCurrentTeamId failed');
    	if (con.getTask() == null) 
    		System.assert(true,'getTask failed');
    	if (con.getTeamMember() == null) 
    		System.assert(true,'getTeamMember failed');
    	if (con.getTeamMembers() == null) 
    		System.assert(true,'getTeamMembers failed');
    		
    	con.genPermissions();
    	if(con.getUserLocale() == null) 
    		System.assert(true,'getUserLocale failed');
    	
    	con.getCurrentProject();
    	
    	ProjectTask__c pT = new ProjectTask__c();
    	pT.team__c = GenerateEnvironmentTest.newTeam.Id;
		pT.StartDate__c = System.now();
		pT.EndDate__c = System.now();
		pT.Duration__c = 1;
		pT.Percent_Completed__c = 0;
		pT.Milestone__c = true; 
		
		con.setTeamMember(GenerateEnvironmentTest.newTeamMember);  
    	con.setNewProyect(pT);
    	con.insertMilestone();
    	con.dummyRefresh();
    	
    	Test.stopTest();
	}

}