trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/classes/WikiNewPageWidgetController.cls
public with sharing class WikiNewPageWidgetController {
	
	public String idTeam = System.currentPageReference().getParameters().get('id');
	public String idWikiPage = System.currentPageReference().getParameters().get('idWP');
	public String idTeamOverview = System.currentPageReference().getParameters().get('tid');
	
	/**
	* Return the Namespace Prefix
	*/
	public String getNamespace () {
        return TeamUtil.getNamespace();
    } 
	
	public void setIdTeam (String idTeam) {
		this.idTeam = idTeam;
	}
	
	public void setIdWikiPage (String idWikiPage) {
		this.idWikiPage = idWikiPage;
	}
	
	public void setIdTeamOverview (String idTeamOverview) {
		this.idTeamOverview = idTeamOverview;
	}
	
	public WikiNewPageWidgetController () {
		constructMethods();
	}
	
	public void constructMethods () {
		if (idTeam != null || idWikiPage != null || idTeamOverview != null) {
			if (idTeamOverview != null && idTeamOverview != '') 
				idTeam = idTeamOverview;
			if (idWikiPage != '' && idWikiPage != null) {
				List<WikiPage__c> wikiShareList = [SELECT Team__c From WikiPage__c WHERE id =:idWikiPage];
				if (wikiShareList.size() > 0) {
					idTeam = wikiShareList[0].Team__c;
				}else {
					throw new CustomException('Insufficient Privileges');	
				}
			}
		}
	}

	public String getIdTeam () {
		return idTeam;
	}
	
	public String getIdTeamOverview () {
		return idTeamOverview;
	}
	
	public String getIdWikiPage () {
		return idWikiPage;	
	}
	
	public void refreshWikis () {}
	
	
	/* Save new Wiki Page */
	public WikiPage__c newWikiPage = new WikiPage__c();
	
	public WikiPage__c getNewWikiPage () {
		return newWikiPage;
	}
		
	public PageReference saveWiki () {
		if (idWikiPage != null && idWikiPage != '') 
			newWikiPage.Parent__c = idWikiPage;
		newWikiPage.Team__c = idTeam;
		newWikiPage.Body__c = '=== Congratulations! === \n You created a new wiki page for your team. Begin by clicking the "Edit" button above to modify this page.';
		insert newWikiPage;
		
		if (idWikiPage == null && idTeamOverview == null) {
			TeamsWidgetWikiDirectoryController directory = new TeamsWidgetWikiDirectoryController();
			if (directory.getWikiPagesCount() == 0) {
				directory.setWikiPagesCount(1);
			}	
		}
		newWikiPage = new WikiPage__c();
		return null;
	}
	
	public PageReference saveWikiAndEdit () {
		if (idWikiPage != null && idWikiPage != '') 
			newWikiPage.Parent__c = idWikiPage;
		newWikiPage.Team__c = idTeam;
		newWikiPage.Body__c = '=== Congratulations! === \n You created a new wiki page for your team. Begin by clicking the "Edit" button above to modify this page.';
		insert newWikiPage;
		
		PageReference pageRef = new PageReference('/apex/WikiPageEdit?id=' + newWikiPage.Id);
		pageRef.setRedirect(true);
		return pageRef;
	}
		
}