trunk/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>TeamType__c</fullName>
        <label>Team Type</label>
        <referenceTo>TeamType__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/TeamType__c.object
<CustomObject>
    <label>Team Type</label>
    <nameField>
        <label>TeamType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

tags/0.1/src/classes/TeamsRedirectController.cls
public class TeamsRedirectController {
	
	public String teamId = System.currentPageReference().getParameters().get('id');
	
	Team__c team = new Team__c();	
	TeamType__c teamtype = new TeamType__c();
	
	public TeamsRedirectController() {
		try {
			team = [SELECT TeamType__c
			       					 	  	FROM Team__c
			       					 	  	WHERE Id =: teamId];
			
			 				 	  		
			teamtype = [SELECT 	Id	 	  	FROM TeamType__c
			       					 	  	WHERE Id =: team.TeamType__c];
			 
		} catch(Exception e) {
		
			System.Debug('the error' + e);
		}
	
	}
	
	public PageReference redirect() {
				
		if(team.TeamType__c == null) return System.currentPageReference();

		String pageurl = '/apex/TeamsDetail' + teamtype.Id + '?id=' + teamId;   		  
		
		System.debug('pageurl = ' + pageurl );
		
		PageReference pr = new PageReference(pageurl);  
		
		pr.setRedirect(true);     					 

		return pr;
	}

}