trunk/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/classes/TeamDetailsWidgetController.cls
public without sharing class TeamDetailsWidgetController {
	
	// Get Team Id Attribute
	String team;
	
	// Setter method for Team Id variable
	public void setTeam(String tID) {
		team = tID;
	}
	
	public String getTeam(){
		return team;
	}
	
	// Active user ID
	public String USERID =  UserInfo.getUserId();
	
	public String getCurrentUser(){
		return USERID;
	}
	
	/**
	* Return the Namespace Prefix
	*/
	public String getNamespace () {
        return TeamUtil.getNamespace();
    } 
	
	Team__c teamspace = new Team__c();
	
	public TeamDetailsWidgetController(){}

    /* ---------------------------- */
   	/*   	 SHARING RULES			*/
   	/* ---------------------------- */	
	public UserPermissions userPermissions = TeamsDetailController.userPermission.clone();
	
	public void genPermissions() {
		userPermissions.setId(UserInfo.getUserId());
		userPermissions.setTeam(team);
		userPermissions.setObjectType('Team');
		userPermissions.setPermissions();		
	}

	public UserPermissions getUserPermissions () {
		return userPermissions;
	}	
	/* ---------------------------- */			
		
		        
	public Team__c getTeamspace() {
		try {
			teamspace = [Select  t.SystemModstamp, 
									t.OwnerId, t.Name,						
									t.LastModifiedDate,
									t.LastModifiedById, 
									t.IsDeleted,
									t.Id, 
									t.Description__c,
									t.Picture__c, 
									t.CreatedDate, 
									t.CreatedById 
									From Team__c t 
									where id =: team];
									
			// The following is to clean text for the widget
			teamspace.Description__c = teamspace.Description__c.replaceAll('[\n\r]*','');
			teamspace.Description__c = teamspace.Description__c.replaceAll('[\n]*',''); 
		
			genPermissions();									
		} catch(Exception e){
			
		}
		
    	return teamspace;
    }
    
     /**
    * Look if the user is a team member
    */    
    public boolean getIsTeamMember(){
    	List<TeamMember__c> tmember = new List<TeamMember__c>();
    	
    	try{
    		tmember = [Select TeamProfile__r.Name, TeamProfile__c From TeamMember__c where User__c =: USERID and Team__c =: team];
    	} catch(Exception e){}
    	
    	boolean res = tmember.size() > 0;
    	tmember.clear();
    	return res;
    }
    
    /**
    * Send id of teammember (if any)
    */
    public String getTeamMemberId(){
    	List<TeamMember__c> tmember = new List<TeamMember__c>();
    	
    	try{
    		tmember = [Select TeamProfile__r.Name, TeamProfile__c From TeamMember__c where User__c =: USERID and Team__c =: team];
    	} catch(Exception e){}
    	
    	if(tmember.size() > 0){
    		Id teamMemberId = tmember[0].Id;
    		tmember.clear();	    	
	    	return teamMemberId; 	    	
    	}else {
    		tmember.clear();
    		return 'no';
    	}    	 
    }
    
    
    /**
    * Look if the user is the team admin
    */    
    public boolean getIsTeamAdmin(){
    	TeamMember__c tmember = new TeamMember__c();    	
    	
    	try{
    		tmember = [Select TeamProfile__r.Name, TeamProfile__c From TeamMember__c where User__c =: USERID and Team__c =: team];
    	} catch(Exception e){}

    	return ((tmember != null) && (tmember.TeamProfile__r.Name == 'Team Administrator'));
    }
    
    /**
    * Get The list of admins to this team
    */
    public String getTeamAdmins(){
    	List<TeamMember__c> tmemberList = new List<TeamMember__c>();
    	
    	try {
    		tmemberList = [Select User__r.Name, User__c From TeamMember__c where TeamProfile__r.Name = 'Team Administrator' and Team__c =: team];
    	} catch (Exception e){
    		throw e;
    	}
    	
    	String teamMemberList = ' ';
    	
    	if(tmemberList.size() > 0 ){ 
	    	for(TeamMember__c tm: tmemberList){
	    		teamMemberList += '<a href="PeopleProfileDisplay?id=' + tm.User__c + '" >'+ tm.User__r.Name +'</a><br />';    	
	    	}     	
    	}
    	tmemberList.clear();
    	return teamMemberList;
    }
    
    /**
    * Get The count of members at the team
    */
    public Integer getTeamCount(){
    	List<TeamMember__c> tmemberList = new List<TeamMember__c>();
    	
    	try {
    		tmemberList = [Select Id From TeamMember__c where Team__c =: team];
    	} catch (Exception e){
    		throw e;
    	}
    	return tmemberList.size();
    }
    
    
    
    public String getTeamspaceImage() {
    	if(teamspace.Picture__c == null) 
    		return '';
    	return '/servlet/servlet.FileDownload?file=' + teamspace.Picture__c;   		
    }
    
    /**
    * Leave a Team
    *@void
    */
    public void leaveTeam (){
    	try{
	    	TeamMember__c member = [select Id from TeamMember__c where User__c =: UserInfo.getUserId() and Team__c =: teamspace.Id];
	    	delete member;
    	}catch(Exception e){
    		throw e;
    	}
    }
    
	
}