trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.5/src/classes/WikiTeamOverviewControllerTest.cls
@IsTest private class WikiTeamOverviewControllerTest {  

    public static testMethod void WikiTeamOverviewController() {
        GenerateEnvironmentTest.gen();
		
		Test.startTest();
        
        WikiTeamOverviewController wtoc = new WikiTeamOverviewController();  
        
     	Team__c newTeam = GenerateEnvironmentTest.newTeam;
        
        wtoc.setTEAMID(newTeam.Id); 
        
        wtoc.getTEAMID();
        
        //UserPermissionsTest.UserPermissionsTest(); 
        
        /* TeamWikis class */
        WikiTeamOverviewController.TeamWikis teamWikis = new WikiTeamOverviewController.TeamWikis();
        
        teamWikis.getId();
        teamWikis.getName();
        teamWikis.getDescription();
        teamWikis.getPicture();
        
        /* Wiki class */
        WikiTeamOverviewController.Wiki wikiClass = new WikiTeamOverviewController.Wiki();
        
        wikiClass.getModifiedByPicture();
        wikiClass.getParentName();
        wikiClass.getParentId();
        wikiClass.getName();
        wikiClass.getId();
        wikiClass.getLastModifiedBy();
        wikiClass.getLastModifiedById();
        wikiClass.getLastModifiedDate();
        wikiClass.getShortDescription();
        
        
        if (wtoc.getUserPermissions() == null) {
            System.assert(true, 'Null Permissions');
        }
        
        if (wtoc.getUserPermissionsTeam() == null) {
            System.assert(true, 'Null Permissions');
        }
        
      
        wtoc.genContructor();
        wtoc.getCurrentTeam();
        wtoc.getWpl();
        
         // Create a new Wiki Child
        WikiPage__c newWiki = new WikiPage__c();
        newWiki.Name = 'Foo Child Wiki';
        newWiki.Team__c = GenerateEnvironmentTest.newTeam.Id;
        newWiki.Body__c = 'Foo Body';
        newWiki.Parent__c = GenerateEnvironmentTest.newWiki.Id;
        insert newWiki;
        
        wtoc.genContructor();
        
        wtoc.trunkText('aaa ra ra fkjdsaf;lkjdsaf;lkjdsaflkjdsaf;lkjdsalkfjlkdsajflkdsajf;lkdsa');
        wtoc.getWikiSites();
        wtoc.getRecentlyUpdated();
        wtoc.getFavorite();
        wtoc.getCntFav();
        wtoc.getMyRecentChanges();
        wtoc.getCntMyRecentChanges(); 
        

        
        Test.stopTest();
    }
}