branches/0.2/src/objects/Bookmark__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BookmarkURL__c</fullName>
        <label>Bookmark Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Comment Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Bookmarks</relationshipLabel>
        <relationshipName>Bookmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>imageUrl__c</fullName>
        <label>imageUrl</label>
        <type>Url</type>
    </fields>
    <label>Bookmark</label>
    <nameField>
        <label>Bookmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookmarks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.1/src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Bookmark__c</fullName>
        <label>Parent Bookmark</label>
        <referenceTo>Bookmark__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>ParentBookmark</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Comment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Comment__c.object
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.1/src/classes/BookmarkTeamOverviewController.cls
public class BookmarkTeamOverviewController {

	Team__c teamspace;
	
	public BookmarkTeamOverviewController() {
		
		teamspace = [SELECT Name
					 FROM Team__c
					 WHERE Id =: System.currentPageReference().getParameters().get('id')];
	}
	
	public Team__c getTeamspace() {
		return teamspace; 
	}
	
	public List<BookmarkGroup> getMyTeam() {
				
		
		// get list
		List<Bookmark__c> myTeams = [SELECT Title__c,
									  		    Team__c,
									  		    
									  			Body__c,
									  			Comments__c,
									  			// Comment__c,
									  			BookmarkURL__c,
									  			ImageUrl__c,									  			
									  			CreatedDate,
									  			CreatedById
							   			 FROM Bookmark__c
							   			 WHERE Team__c =: teamspace.Id
							   			 ORDER BY CreatedDate DESC
							             LIMIT 10];
				

		return sortBookmarks(myTeams);
	}
	
	public List<BookmarkGroup> getAllTeam() {
		
		// get list
		List<Bookmark__c> allTeams = [SELECT Title__c,
									  			 Team__c,
									  			 
									  			 Body__c,
									  			 Comments__c,
									  			//  Comment__c,
									  			 BookmarkURL__c,
									  			 ImageUrl__c,									  			 
									  			 CreatedDate,
									  			 CreatedById
							   			  FROM Bookmark__c
							   			  ORDER BY CreatedDate DESC
							              LIMIT 10];
		
		return sortBookmarks(allTeams);

	}
	
	/*
	 * sort into bookmark groups
	 */
	private List<BookmarkGroup> sortBookmarks(List<Bookmark__c> bookmarks) {
		
		List<BookmarkGroup> groupList = new List<BookmarkGroup>();
		BookmarkGroup currentGroup = null;
		
		for(Bookmark__c a: bookmarks) {			
		
			if(currentGroup == null || 
			   !currentGroup.getPostedDate().isSameDay(a.CreatedDate)) {
			    currentGroup = new BookmarkGroup(a.CreatedDate);
			    currentGroup.addBookmark(a);		   	
				groupList.add(currentGroup);
			} else {
				currentGroup.addBookmark(a);
			}
				
		}	
		
		return groupList;
	}
	
	public class BookmarkGroup {
		
		List<Bookmark__c> bookmarks = new List<Bookmark__c>();
		Datetime postedDate;
		
		public BookmarkGroup (Datetime a) {
			postedDate = a;
		}
		
		public Datetime getPostedDate() {
			return postedDate;
		}
		
		public String getFormatedPostDate() {
			return postedDate.format('MMMM dd, yyyy');
		}
		
		public void addBookmark(Bookmark__c a) {
			bookmarks.add(a);
		}
		
		public List<Bookmark__c> getBookmarks() {
			return bookmarks;
		}
	}
}