branches/0.2/src/objects/Bookmark__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Bookmarks</relationshipLabel>
        <relationshipName>Bookmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bookmark</label>
    <nameField>
        <label>Bookmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookmarks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.3/src/classes/TeamsWidgetRecentBookmarkTest.cls
@IsTest private class TeamsWidgetRecentBookmarkTest {
    public static testMethod void testTeam() {
        try{
            //
            TeamsWidgetRecentBookmarkController team = new TeamsWidgetRecentBookmarkController();
            Team__c t = [select Id from Team__c limit 1];
            team.setTeamspaceId(t.Id);
            Id teamId = team.getTeamspaceId();
            List<Bookmark__c> bookmarks = team.getRecentBookmarks();
            team.setTeamspaceId(null); 
            bookmarks = team.getRecentBookmarks();
        }catch(Exception e){
            throw e;
        }
    }   
}