branches/0.2/src/objects/Bookmark__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Bookmarks</relationshipLabel>
        <relationshipName>Bookmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bookmark</label>
    <nameField>
        <label>Bookmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookmarks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.3/src/classes/TeamsWidgetRecentBookmarkController.cls
public class TeamsWidgetRecentBookmarkController {

	public Id teamspaceId;
	
	public TeamsWidgetRecentBookmarkController() {
		teamspaceId = System.currentPageReference().getParameters().get('id');
	}
	
	public void setTeamspaceId(String s){
		teamspaceId = s;
	}
	
	public Id getTeamspaceId() {
		return teamspaceId;
	}
	
	public List<Bookmark__c> getRecentBookmarks() {
		if(teamspaceId == null) 
			return new List<Bookmark__c>();
		List<Bookmark__c> bookmarks = new List<Bookmark__c>();
		try { 
			bookmarks = [SELECT Title__c
										   FROM Bookmark__c
										   WHERE Team__c =: teamspaceId
										   ORDER BY CreatedDate DESC
										   LIMIT 5];
		} catch(Exception e){
			System.debug('\n ////////////////////////////////////////// \n ' + e);		
		}
		if(bookmarks.size() > 0){
			return bookmarks;
		} else {
			return new List<Bookmark__c>();
		}
	}

}