src/objects/BlogEntry__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TeamsWidgetAnnouncementWideTest.cls
@IsTest private class TeamsWidgetAnnouncementWideTest {
	public static testMethod void testTeam() {
		try{
			TeamsWidgetAnnouncementWideController team = new TeamsWidgetAnnouncementWideController();
			
			Team__c t = [select Id from Team__c limit 1];
			team.setTeamId(t.Id);
			team.getTeam();
			t = team.getTeamspace();
			
			BlogEntry__c announcement = [select Id, CreatedDate from BlogEntry__c limit 1];
			TeamsWidgetAnnouncementWideController.AnnouncementWrapper annou = new TeamsWidgetAnnouncementWideController.AnnouncementWrapper(announcement);
	    	annou.getFormatedPostDate();
	    	annou.getFormatedPostTime();
	    	annou.getDetail();
	    	team.getRecentAnnouncements();
	    	
		}catch(Exception e){
			throw e;
		}		
	}		
}