src/objects/BlogEntry__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.5/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.2/src/classes/TeamsWidgetRecentAnnouncementController.cls
public class TeamsWidgetRecentAnnouncementController {
	
	public Id teamspaceId;
	
	public TeamsWidgetRecentAnnouncementController() {
		teamspaceId = System.currentPageReference().getParameters().get('id');
	}
	
	public void setTeamspaceId(String s){
		teamspaceId = s;
	}
	
	public Id getTeamspaceId() {
		return teamspaceId;
	}
	
	public List<BlogEntry__c> getRecentAnnouncements() {
		if(teamspaceId == null) 
			return new List<BlogEntry__c>();
		List<BlogEntry__c> announcements = [select Title__c
									   		   from BlogEntry__c
									   		   where Team__c =: teamspaceId
									  		   order by CreatedDate desc
									   		   limit 5];
		return announcements;
	}

}