src/objects/BlogEntry__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.1/src/classes/TeamsWidgetAnnouncementWideController.cls
public class TeamsWidgetAnnouncementWideController {
	
	Team__c teamspace;
	
	public TeamsWidgetAnnouncementWideController() {
		
		teamspace = [SELECT Name
					 FROM Team__c
					 WHERE Id =: System.currentPageReference().getParameters().get('id')];
	}
	
	public Team__c getTeamspace() { 
		return teamspace;
	}
	
	public List<AnnouncementWrapper> getRecentAnnouncements() {
				
		List<AnnouncementWrapper> announcements = new List<AnnouncementWrapper>();
		
		// get list
		for(BlogEntry__c a: [SELECT Title__c,
									   Team__c,
									   Message__c,
							  		   CreatedDate,
							  		   CreatedById							  									  			
					   			 FROM BlogEntry__c
					   			 WHERE Team__c =: teamspace.Id
					   			 ORDER BY CreatedDate DESC
					             LIMIT 5]) {
			announcements.add(new AnnouncementWrapper(a)); 	
		}
				

		return announcements;
	}
	
	public class AnnouncementWrapper {
		
		BlogEntry__c announcement;
		
		public AnnouncementWrapper (BlogEntry__c a) {
			announcement = a;
		}
		
		public String getFormatedPostDate() {
			return announcement.CreatedDate.format('MMMM dd, yyyy');
		}
		
		public String getFormatedPostTime() {
			return announcement.CreatedDate.format('hh:mm aaa');
		}
		
		public BlogEntry__c getDetail() {
			return announcement;
		}
	}
}