src/objects/BlogEntry__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.3/src/classes/TeamsWidgetRecentAnnouncementTest.cls
@IsTest private class TeamsWidgetRecentAnnouncementTest {
    public static testMethod void testTeam() {
        try{
            TeamsWidgetRecentAnnouncementController team = new TeamsWidgetRecentAnnouncementController();
            Team__c t = [select Id from Team__c limit 1];
            team.setTeamspaceId(t.Id);
            Id teamId = team.getTeamspaceId();
            List<BlogEntry__c> blogs = team.getRecentAnnouncements();
            team.setTeamspaceId(null);
            blogs = team.getRecentAnnouncements();          
        }catch(Exception e){
            throw e;
        }
    }
}