src/objects/BlogEntry__c.object
<CustomObject>
    <fields>
        <fullName>CommentCount__c</fullName>
        <label>Comment Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>Posted By</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublishedDate__c</fullName>
        <label>PublishedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Blog</label>
    <nameField>
        <label>Blog</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateBlogs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateBlogs</label>
        <type>Checkbox</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TeamsWidgetRecentBlogsController.cls
public class TeamsWidgetRecentBlogsController {
  // Get Team Id Attribute
	
	String teamIdBlog;
	
	// Setter method for Team Id variable
	public void setTeamIdBlog(String tID) {
		teamIdBlog = tID;		
	}
	
	public String getTeamIdBlog(){
		return teamIdBlog;
	}
  
  	 Integer blogCount;
  	 String userId = UserInfo.getUserId();
  
     public List<BlogEntry__c> getBlogs() {
	    List<BlogEntry__c> myBlogs = new List<BlogEntry__c>();	
		myBlogs =  [Select  b.Title__c, 
					b.Team__c, 
					b.Id,
					b.PublishedDate__c, 
					b.PostedBy__r.Name, 
					b.PostedBy__r.Id,
					b.PostedBy__c, 
					b.CommentCount__c 
					From 
					BlogEntry__c b where b.PublishedDate__c != null and b.Team__c =: teamIdBlog
					order by b.PublishedDate__c  
					desc limit 8
						];
						
		
		blogCount = myBlogs.size();
		
    	return myBlogs;
    } 
    
    public Boolean getnewPrivileges() {
    	List<TeamMember__c> tm = new List<TeamMember__c>();	
    	tm  = [Select 
    					t.User__c, 
    					t.Team__c, 
    					t.TeamProfile__r.CreateBlogs__c, 
    					t.TeamProfile__c From TeamMember__c t 
    					where t.Team__c =: teamIdBlog and t.User__c =: userId ];
		Boolean result;
		if(tm.size() > 0){
			result = tm[0].TeamProfile__r.CreateBlogs__c;
			return result;
		} else {
			return false;
		}
    }
    
     public Integer getblogCount(){
	        return blogCount;
    }
    
    public void setblogCount(Integer count){
    	blogCount = count;
    	
    }
	       
    					
}