src/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ViewCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>ParentTeam__c</fullName>
        <label>Parent Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>ParentTeam</relationshipLabel>
        <relationshipName>ParentTeam</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DiscussionWidgetSubTeamsController.cls
public class DiscussionWidgetSubTeamsController {
	
	public String teamId = System.currentPageReference().getParameters().get('id');
	
	public boolean noSubTeams;
	
	public void setTeamId (String teamId) {
		this.teamId = teamId;
	}
	
	/*
	*@construct
	*/
	public DiscussionWidgetSubTeamsController(){
		
	}
	
	/*
	*@void
	*/
	public List<subTeams> getSubTeams(){
		return getSubTeam(teamId);
	}

 	public class subTeams {
 		String name;
 		Integer count;
 		String id;
        public String getName () {
        	return name;
        } 
        public String getId () {
        	return id;
        }        
        public Integer getCount () {
        	return count;
        } 
        public void setName (String name) {
        	this.name = name;
        }
        public void setId (String id) {
        	this.id = id;
        }        
        public void setCount (Integer intCount) {
        	//Integer intCount = Integer.valueOf(String.valueOf(Math.roundToLong(countDouble)));
        	this.count = intCount;
        }                              		
 	
 	}
	
	public Integer getCountSubTeams () {
		return 	[Select Id From Team__c where parentTeam__c =: teamId].size();
	}
	
	public List<subTeams> getSubTeam(String teamId){
			
 		List<subTeams> subTeamsCount = new List<subTeams>();
 		
 		for (Team__c item: [Select Name,Id From Team__c where parentTeam__c =: teamId order by CreatedDate desc limit 4]) {
 			subTeams subTeam = new subTeams();
 			Integer count;
 			List<DiscussionTopic__c> msjCount = [SELECT 
						Id, 
						ViewCount__c, 
						Team__c, 
						Team__r.Name,
						Subject__c, 
						Name, 
						MessageCount__c, 
						CreatedBy.Name,
						CreatedBy.Id,
						LastPostedMessage__c, 
						DiscussionForum__c 
						From DiscussionTopic__c where Team__c =: item.Id];
 			subTeam.setCount(msjCount.size());
 			subTeam.setName(item.Name);
 			subTeam.setId(item.Id);
 			subTeamsCount.add(subTeam);		
 		}
 		return subTeamsCount;	
	}
	
}