src/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectAssignee__c.object
<CustomObject>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <label>Project Task</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectAssignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Assignees</relationshipLabel>
        <relationshipName>Assignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectAssignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Project Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectAssignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/ProjectTask__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Duration (Days)</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentTask__c</fullName>
        <label>Parent Task</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ParentTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent_Completed__c</fullName>
        <label>Percent Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>ProjectTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>name</fullName>
        <active>true</active>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProjectTaskDetailTest.cls
@IsTest private class ProjectTaskDetailTest {
    public static testMethod void testProject() { 
		try{
	        ProjectTaskDetailController project = new ProjectTaskDetailController();
	        
	        //
	        ProjectTask__c projectTask = [select 	p.Id,
				                                    p.Team__c,
				                                    p.Team__r.Name, 
				                                    p.Startdate__c, 
				                                    p.Priority__c, 
				                                    p.ParentTask__c, 
				                                    p.Percent_Completed__c,
				                                    p.Name, 
				                                    p.Milestone__c, 
				                                    p.LastModifiedById, 
				                                    p.EndDate__c, 
				                                    p.Duration__c, 
				                                    p.Description__c, 
				                                    p.CreatedById, 
				                                    (Select Id, User__c From ProjectAssignee__r) 	        
				         						from ProjectTask__c p limit 1];
				         						
				         						
			project.param = projectTask.Id;
			project.getTask(projectTask.Id);
	        project.genPermissions();
	        project.getUserPermissions();			
			//project.markComplete();		

	        //
	        ProjectTaskDetailController.TaskDetails TaskDetail   = new ProjectTaskDetailController.TaskDetails();	        
	        TaskDetail.id = projectTask.Id;
	        String id = TaskDetail.id;
	            
	        //
	        ProjectTaskDetailController.ProjectAssignee assigns = new ProjectTaskDetailController.ProjectAssignee();
	        assigns.getId();
	        assigns.setId('Id');
	        assigns.setName('Name');
	        assigns.getPercent();
	        assigns.setPercent(1);
	        
	        //
	        ProjectTaskDetailController.AttachmentInfo attach = new ProjectTaskDetailController.AttachmentInfo();
	        attach.getId();
	        attach.setId('');
	        attach.getName();
	        attach.setName('Name');
	        attach.getAttachImage();
	        attach.setAttachImage('');
	        
	        //
	        TaskDetail.Name = projectTask.Name;
	        String name = TaskDetail.Name;
	        
	        TaskDetail.TeamName = projectTask.Team__r.Name;
	        String teamName = TaskDetail.TeamName;
	        
	        TaskDetail.Priority = projectTask.Priority__c;
	        String priority = TaskDetail.Priority;
	        
	        TaskDetail.Startdate = ((projectTask.Startdate__c).format('MM/dd/yyyy'));
	        String startdate = TaskDetail.Startdate;
	        
	        TaskDetail.DueDate = ((projectTask.EndDate__c).format('MM/dd/yyyy'));
	        String dueDate = TaskDetail.DueDate;
	        
	        TaskDetail.Estimate = (projectTask.Duration__c).intValue();
	        Integer estimate = TaskDetail.Estimate;
	         
	        TaskDetail.Description = projectTask.Description__c;
	        String description = TaskDetail.Description;
	        
	        UserPermissionsTest.UserPermissionsTest();	
		
		}catch(Exception e){
			throw e;
		}
    }
}