src/objects/EducationHistory__c.object
<CustomObject>
    <label>Education History</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/EmploymentHistory__c.object
<CustomObject>
    <label>Employment  History</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment  History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/main/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UserCompetencies__c.object
<CustomObject>
    <label>User Competencies</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Competencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TeamsWidgetRecentActivitiesTest.cls
@IsTest private class TeamsWidgetRecentActivitiesTest {

    public static testMethod void testTeam() {
        
        try{
            TeamsWidgetRecentActivitiesController team = new TeamsWidgetRecentActivitiesController();   
            List<TeamsWidgetRecentActivitiesController.miniFeed> feeds=team.getMiniFeeds(); 
            Team__c t = [select Id from Team__c limit 1];
            team.setTeamId(t.Id);
            TeamsWidgetRecentActivitiesController.miniFeed feed = new TeamsWidgetRecentActivitiesController.miniFeed();
            
            List<String> types = new List<String>();
            types.add('EducationHistory__c');
            types.add('UserCompetencies__c');
            types.add('DiscussionThread__c');
            types.add('EmploymentHistory__c');
            types.add('Announcement__c');
            types.add('TeamMember__c');
            
            Integer cant = types.size();
            for(Integer i = 0; i < cant ; i++){
                feed.setTypeOfFeed(types[i]);
                feed.getTypeOfFeed();
            }
            
            feed.setName('Name');
            feed.setUser('User');
            feed.setMessage('Message');
            Datetime myDateTime = Datetime.now();
            feed.setFeedDate(myDateTime);
            feed.setFeedDateString('DateTimestring');
            feed.setFeedDateClass('feedDateClass');
            
            String teamId = team.getTeamId();
            String name = feed.getName();
            String userName = feed.getUser();
            String message = feed.getMessage();
            Datetime d = feed.getFeedDate();
            String feedDate = feed.getFeedDateString();
            String feedClass = feed.getFeedDateClass();

        }catch(Exception e){
            throw e;
        }
    
    }

}