src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamSubscription__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionNewReply__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DiscussionNewReply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscussionNewTopic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DiscussionNewTopic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscussionReplyToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DiscussionReplyToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignToMeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignToMeChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignedToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignedToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamMemberJoinLeave__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TeamMemberJoinLeave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamMemberStatusUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TeamMemberStatusUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>TeamSuscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamSuscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WikiCreatedByMeUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiCreatedByMeUpdated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WikiNewPage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiNewPage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WikiPageUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WikiPageUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>TeamSubscription</label>
    <nameField>
        <label>TeamSubscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TeamSubscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TeamsSubscriptionController.cls
public class TeamsSubscriptionController {
	
	public String idTeam = System.currentPageReference().getParameters().get('id');
	
	Integer subscriptionCount;
	
	public Integer getSubscriptionCount () {
		return subscriptionCount;
	}
	
	public TeamSubscription__c subscription = new TeamSubscription__c();
	
	public TeamSubscription__c getSubscription () {
		return subscription;
	}
	
	public void setIdTeam (String idTeam) {
		this.idTeam = idTeam; 
	}
	
	public String getIdTeam () {
		return idTeam;
	}
	
	public TeamsSubscriptionController () {
		constructMethods(); 
	}
	
	public void constructMethods () {
		if (idTeam != null) {
			List<TeamSubscription__c> teamSubList = new List<TeamSubscription__c>();
			teamSubList = [select id,    
							TeamMemberStatusUpdated__c,
							TeamMemberJoinLeave__c, 
							DiscussionNewTopic__c,
							DiscussionNewReply__c,
							DiscussionReplyToMe__c,
							ProjectTaskAssignedToMe__c,
							ProjectTaskAssignToMeChanged__c,
							ProjectTaskChanged__c,
							ProjectTaskDeleted__c,
							WikiCreatedByMeUpdated__c,
							WikiNewPage__c,
							WikiPageUpdated__c,
							Team__c,
							User__c
						from TeamSubscription__c where User__c =:UserInfo.getUserId() and Team__c =: idTeam limit 1];
			if (teamSubList.size() > 0 ) {
				subscription = teamSubList[0];
			}	
			subscriptionCount = teamSubList.size();
		}
	}
	
	public PageReference saveSubscription () {
		if (subscriptionCount > 0) {
			update 	subscription;	
		}	
		else {
			subscription.Team__c = idTeam;
			subscription.User__c = UserInfo.getUserId();
			insert subscription;
		}
		PageReference pageRef = new PageReference('/apex/TeamsRedirect?id=' + idTeam);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	public PageReference cancelSubscription () {
		PageReference pageRef = new PageReference('/apex/TeamsRedirect?id=' + idTeam);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	public PageReference deleteSubscription () {
		if (subscription != null && subscriptionCount > 0 ) {
			delete subscription;
		}
		PageReference pageRef = new PageReference('/apex/TeamsRedirect?id=' + idTeam);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	
}