src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>TeamType__c</fullName>
        <label>Team Type</label>
        <referenceTo>TeamType__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/TeamType__c.object
<CustomObject>
    <label>Team Type</label>
    <nameField>
        <label>TeamType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AdminTeamTypeListTest.cls
@IsTest private class AdminTeamTypeListTest {
    public static testMethod void testAdmin() {
        try{
        	GenerateEnvironmentTest.gen();
        	Test.startTest();		
	        GenerateEnvironmentTest.createTeamType();
	        AdminTeamTypeListController admin = new AdminTeamTypeListController();
	        TeamType__c teamType = [select Id, Name, CreatedDate, (Select Id From Teams__r), CreatedById from TeamType__c limit 1];
	        AdminTeamTypeListController.TeamTypes teamTypes =  new AdminTeamTypeListController.TeamTypes(teamType);
	        List<AdminTeamTypeListController.TeamTypes> profiles = admin.getTypes();
	        teamTypes.getCreatedDate();
	        teamTypes.getTeams();
	        teamTypes.getTeamType();
	        
			Test.stopTest();	        
        }catch(Exception e){
        	throw e;
        }
    } 
}