src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TeamsWidgetWikiController.cls
public class TeamsWidgetWikiController {


	Id teamspaceId = System.currentPageReference().getParameters().get('id');
	
	public void setTeamspaceId (Id teamspaceId) {
		this.teamspaceId = teamspaceId;	
	}
	
	public Id getTeamspaceId() {
		return teamspaceId;
	}
	
	public List<WikiPage__c> getWikiPages() {
		List<WikiPage__c> pages = new List<WikiPage__c>();
		if(teamspaceId !=null) {
			pages = [SELECT Name
									   FROM WikiPage__c
									   WHERE Team__c =: teamspaceId
									   ORDER BY LastModifiedDate DESC
									   LIMIT 5];
		}
		return pages;
	}
	
	
	public Integer getWikiPagesSize(){
		List<WikiPage__c> wikis = getWikiPages();
		
		return wikis.size();		
	}

}