src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TeamsWidgetWikiDirectoryControllerTest.cls
@IsTest private class TeamsWidgetWikiDirectoryControllerTest { 
    public static testMethod void testWiki() {
        GenerateEnvironmentTest.gen();
		
		Test.startTest();
        
        TeamsWidgetWikiDirectoryController wiki = new TeamsWidgetWikiDirectoryController();
        UserPermissions userPermissions = new UserPermissions();
        
        userPermissions = new UserPermissions();
		
		wiki.setSidebar(true);
        wiki.getSidebar();        
        
        String idTeam = GenerateEnvironmentTest.newTeam.Id;
        wiki.setTeamId(idTeam);
        
        if (wiki.getTeamId() == null) {
            System.assert(true, 'Null Team Id');
        }
        
        if (wiki.getUserPermissions() == null) {
            System.assert(true, 'Null User Permissions');
        }
        
        /* Wikis Class */
      
        WikiPage__c wikiPage = [select id, name, team__c, parent__c, body__c, createdById , createdBy.Name from WikiPage__c where id =:GenerateEnvironmentTest.newWiki.Id];
        wikiPage.Name = 'loooooooooooooooooonnnnnnnnnnnnnnnnnnggggggggggggggg';           
        TeamsWidgetWikiDirectoryController.Wikis wikiClass = new TeamsWidgetWikiDirectoryController.Wikis(wikiPage);
        wikiClass.getWikiPage();
        wikiClass.getName();
        wikiClass.getCreatedByName(); 
        
        wiki.getWikis();
        wiki.getWikiPagesCount();
        
        try {
            wiki.refresh();
        } 
        catch (Exception e) {
            System.assert(true, e);
        }
        
        Test.stopTest();
    }
}