src/objects/Widget__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Gadget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widget</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WidgetUrl__c</fullName>
        <label>WidgetUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InitializeTeamspacesControllerTest.cls
@IsTest private class InitializeTeamspacesControllerTest {
	public static testMethod void test() {
		GenerateEnvironmentTest.gen();
		
		Test.startTest();
		
		InitializeTeamspacesController iniTeams = new InitializeTeamspacesController();
		
		Widget__c newWidget = new Widget__c();
		newWidget.Name = 'Foo Widget';
		newWidget.Type__c = 'Widget';
		newWidget.WidgetUrl__c = 'Foo Url';
		insert newWidget; 
		
		iniTeams.initialize();
		iniTeams.createProfile('Team Administrator');
		iniTeams.createProfile('Read Only');
		iniTeams.createProfile('Individual Contributor');
		
		Test.stopTest();
	}
}