branches/0.1/src/objects/DiscussionMessage__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionTopic__c</fullName>
        <label>Discussion Topic</label>
        <referenceTo>DiscussionTopic__c</referenceTo>
        <relationshipLabel>Discussion Messages</relationshipLabel>
        <relationshipName>DiscussionTopic</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <label>Discussion Message</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

branches/0.1/src/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>PostedBy__c</fullName>
        <label>PostedBy</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>PostedDate</label>
        <type>DateTime</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.1/src/classes/DescussionCreateDataTest.cls
public class DescussionCreateDataTest {
  
  public static testMethod void testDiscussion() {
  	
  	List<DiscussionMessage__c> messageList = [select Id, CreatedById, CreatedDate, PostedBy__c, PostedDate__c from DiscussionMessage__c];
		for (DiscussionMessage__c item: messageList) {
				item.PostedBy__c = item.CreatedById;
				item.PostedDate__c = item.CreatedDate;
		}
		try{
		update messageList;
		} catch (DmlException e) {
			System.assert(false,'No se pudo actualizar el mensaje')	;
		}
     		
		List<DiscussionTopic__c> topicList = [select Id, CreatedById, CreatedDate, PostedBy__c, PostedDate__c from DiscussionTopic__c];
		for (DiscussionTopic__c item: topicList) {
				
				item.PostedBy__c = item.CreatedById;
				System.assert(item.CreatedById==null,'Error Posted by');
				item.PostedDate__c = item.CreatedDate; 
				System.assert(item.CreatedById==null,'Error PostedDate');
		}
		try{
		update topicList;
		}catch (DmlException e) {
		System.assert(false,'No se pudo actualizar los topics')	;
		}
		
	}
  }