tags/0.1/src/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/MiniFeed__c.object
<CustomObject>
    <fields>
        <fullName>FeedDate__c</fullName>
        <label>FeedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Mini Feeds</relationshipLabel>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EducationHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmploymentHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UserCompetencies__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamspaceMember__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DiscussionThread__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcement__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProjectTask__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlogEntry__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WikiPage__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookmark__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamNew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEdit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamDelete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberLeave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberAdd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberJoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditRole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCreateNewType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminEditType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminNewTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleAddNewUser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeoplePhoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEducationChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEmploymentChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleCompetencyChange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MiniFeed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mini Feed</label>
    <nameField>
        <label>Mini Feed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mini Feeds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.1/src/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Current Profile Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusLastModifiedDate__c</fullName>
        <description>Status Last Modified Date</description>
        <inlineHelpText>Status Last Modified Date</inlineHelpText>
        <label>StatusLastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.2/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.1/src/classes/TeamsOverviewController.cls
public class TeamsOverviewController {

    List<TeamMember__c> teams = new List<TeamMember__c>();
    List<MiniFeeds> minifeeds = new List<MiniFeeds>();    
    
    /*
    * Construct
    */
    public TeamsOverviewController(){
    	teams = getMyTeams();
    	if(teams.size() > 0)
    		getFeeds();
    }
    
    	
	/**
	* Check if people profile exist for current user
	* @return PageReference
	*/
	public PageReference profileExist(){
		PageReference pr = null;
		List<PeopleProfile__c> profiles = new List<PeopleProfile__c>();
		profiles = getPeopleProfile();
		if(profiles.size() == 0){
			PeopleProfile__c profile = new PeopleProfile__c();
			profile.User__c = UserInfo.getUserId();
			profile.Name = UserInfo.getName();
			insert profile;
		}
		return pr;
	}
	
	/**
	* Get people profile for current user
	*@return List<PeopleProfile__c>
	*/
	public List<PeopleProfile__c> getPeopleProfile(){
		List<PeopleProfile__c> profiles = new List<PeopleProfile__c>();			
		profiles = [SELECT Id,  Status__c, Picture__c, StatusLastModifiedDate__c
		     		FROM PeopleProfile__c
		     		WHERE User__c =: UserInfo.getUserId()];
		return profiles;	
	}
	
    
    /*
    * Getters
    */
    public List<TeamMember__c> getTeams(){
    	return teams;
    }
    
    public List<MiniFeeds> getMinifeeds(){
    	return minifeeds;
    }    
    
    /*
    *@retrun List<TeamMember__c>
    */    
    public List<TeamMember__c> getMyTeams(){
    	return  [Select s.Team__c, s.Team__r.Id, s.Team__r.Name,
	    			Team__r.Description__c, Team__r.CreatedDate 
	                From TeamMember__c s
    				where s.User__c =: UserInfo.getUserId()
    				order by s.CreatedDate desc
    				limit 15
    			];
    }
    
    /**
    *
    */
    public String getTeamspaceImage() {
    	List<Attachment> attach = [select Id 
        							from Attachment 
        							where ParentId =:System.currentPageReference().getParameters().get('id')];
        	if(attach.size() == 0) return '';					
        	return '/servlet/servlet.FileDownload?file=' + attach[0].Id;
    }
    
    
    /*
    *@void
    */
    public void getFeeds(){
    	List<MiniFeed__c> mf = new List<MiniFeed__c>();    	
    	String allFeeds = System.currentPageReference().getParameters().get('isAllFeeds');
    	if(allFeeds != 'true'){
	    	List<Id> myTeams = new List<Id>();
	    	for(TeamMember__c tm : teams){
	    		if(tm.Team__r.Id != null)
	    			myTeams.add(tm.Team__r.Id); 
	    	}
	
	    	mf = [Select 
	    				m.User__c,
	    				m.User__r.Name, 
	    				m.Type__c, 
	    				m.Message__c, 
	    				m.Id, 
	    				m.CreatedDate 
	    				from MiniFeed__c m
	    				where Team__c in:myTeams
	    				order by m.FeedDate__c desc
	    				limit 25];
    	}else{
	    	mf = [Select 
	    				m.User__c,
	    				m.User__r.Name, 
	    				m.Type__c, 
	    				m.Message__c, 
	    				m.Id, 
	    				m.CreatedDate 
	    				from MiniFeed__c m
	    				order by m.FeedDate__c desc
	    				limit 25];    		
    	}
    	
    	minifeeds.clear();
    	for(MiniFeed__c m : mf){
    		MiniFeeds minif = new MiniFeeds(m);
    		minifeeds.add(minif);
    	}
    }


    /*
    *@class
    */
    public class MiniFeeds {
    	
    	MiniFeed__c feed = null;
    	String formatedDate = null;
    	
    	/**
    	*@param MiniFeed__c
    	*/
    	public MiniFeeds(MiniFeed__c m){
    		feed = m;
    	}
    	
    	public MiniFeed__c getFeed(){
    		return feed;
    	}
    	
    	public String getFormatedDate(){
    		return feed.CreatedDate.format('MMMM dd, yyyy HH:mm');
    	}		
    }
}