tags/0.1/src/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShortDescription__c</fullName>
        <label>ShortDescription</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.6/src/classes/WikiPageLinksController.cls
/**
*@author Juan Bessonart @ 07/07/2008
*/
public class WikiPageLinksController {
	
    public String idWikiPage = System.currentPageReference().getParameters().get('idWP');
    public String teamId = '';
    
	/**
	* Costructor
	*/
	public WikiPageLinksController () {
		genTeamId();
	} 	
 	
 	/**
 	* Read Team for wiki page
 	*/
    public void genTeamId () {
   		teamId = [select id, team__c from WikiPage__c where id=: idWikiPage].team__c;
    }
    
    /**
    *@param String
    */
    public void setIdWikiPage (String idWikiPage) {
    	this.idWikiPage = idWikiPage;	
    }

	/**
	* Class AttachmentInfo
	*/ 	 
	public class AttachmentInfo {
        
        String name;
        String attachImage;
		String id;
        
        /**
        *@return String
        */
        public String getId () {
        	return id;
        }
        
        /**
        *@param String
        */
        public void setId (String id) {
        	this.id = id;
        }
        
        /**
        *@return String
        */
        public String getName() {
        	return name;
        }

        /**
        *@param String
        */
        public void setName(String name) {
                this.name = name;
        }  
        
        /**
        *@return String
        */
        public String getAttachImage() {
                return attachImage;
        }                                
	}
	
    /**
    *@return List<AttachmentInfo>
    */
    public List<AttachmentInfo> getAttachments() {
    	List<Attachment> Attachments = new List<Attachment>();
    	if (idWikiPage == '{!idWikiPage}') {
    		Attachments = [select name, id, parentid, ContentType from attachment order by name];
    	}else {
    		Attachments = [select name, id, parentid, ContentType from attachment where parentid=:idWikiPage order by name];
    	}
    	
		List<AttachmentInfo> infos = new List<AttachmentInfo>();

		for (Attachment item: Attachments){	
            AttachmentInfo info = new AttachmentInfo();
            info.setId(item.Id);
            info.setName(item.Name);
            infos.add(info);
        }	
		return infos;   	    									
    }     
    
    /**
    *@return Integer
    */
    public Integer getCntAttachments () {
    	return [select count() from attachment where parentid=:idWikiPage];
    }
    
	/**
	*@return List<WikiPage__c>
	*/
   	public List<WikiPage__c> getWikiPagesTeam () {
   		List<WikiPage__c> wikis = new List<WikiPage__c>();
   		wikis = [select id, Name, team__r.Name from WikiPage__c where team__c =: teamId and Parent__c !=:idWikiPage  and id !=: idWikiPage order by Name];
   		return wikis;
   	}
   	 
   	/**
   	*@return Integer
   	*/
   	public Integer getCntTeamWikis () {
   		return [SELECT count() FROM WikiPage__c WHERE team__c =: teamId and Parent__c !=:idWikiPage and id !=: idWikiPage]; 
   	}
	
   	/**
   	*@return List<WikiPage__c>
   	*/
   	public List<WikiPage__c> getWikiPagesAll () {
   		List<WikiPage__c> wikis = new List<WikiPage__c>();
   		wikis = [select id, Name, team__r.Name from WikiPage__c where team__c !=: teamId and team__c != null order by Name];
   		return wikis;
   	}
   	
   	/**
   	*@return Integer
   	*/
   	public Integer getCntAllWikis () {
   		return [SELECT count() FROM WikiPage__c WHERE team__c !=: teamId and team__c != null]; 
   	}
   	 
 	/**
 	*@return List<WikiPage__c>
 	*/
 	public List<WikiPage__c> getWikiChilds () {
   		List<WikiPage__c> childs = new List<WikiPage__c>();
	   	childs = [SELECT Id, Name, ShortDescription__c, Body__c, Parent__c FROM WikiPage__c WHERE Parent__c = :idWikiPage order by Name];
		return childs;
   	}  
   	
   	/**
   	*@return Integer
   	*/
   	public Integer getCntWikiChilds () {
   		return [SELECT count() FROM WikiPage__c WHERE Parent__c = :idWikiPage]; 
   	}
}