tags/0.1/src/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tags/0.3/src/objects/DiscussionTopic__c.object
<CustomObject>
    <fields>
        <fullName>DiscussionForum__c</fullName>
        <label>Discussion Forum</label>
        <referenceTo>DiscussionForum__c</referenceTo>
        <relationshipName>DiscussionForum</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastPostedMessage__c</fullName>
        <label>LastPostedMessage</label>
        <referenceTo>DiscussionMessage__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MessageCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Discussion Topics</relationshipLabel>
        <relationshipName>DiscussionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion Topic</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussion Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.6/src/classes/DiscussionOverlayDeleteTopicController.cls
/**
*@author: Bruno Fagundez @ 08-28-2008
*/
public without sharing class  DiscussionOverlayDeleteTopicController {
	
	/**
	* Construct
	*/
	public DiscussionOverlayDeleteTopicController (){}
	
	String topicId = '';
	/**
	* Get Topic Id
	*@return String
	*/
	public String getTopicId() {	
		return topicId;
	}
	
	/**
	* Set Topic Id
	*@param String
	*/
	public void setTopicId(String tID) {	
		topicId = tID;
	}
	
	/**
	* Delete Topic by Id
	*/
	public void deleteTopic(){
		DiscussionTopic__c topicToDelete = [select Id, LastPostedMessage__c, Team__c, MessageCount__c 
											from DiscussionTopic__c 
											where Id =: topicId];
		DiscussionForum__c discForum = [select Id, LastPostedMessage__c, Team__c, MessageCount__c 
										from DiscussionForum__c 
										where Team__c =: topicToDelete.Team__c];
		discForum.MessageCount__c = discForum.MessageCount__c - topicToDelete.MessageCount__c;
		update discForum;
		delete topicToDelete;
	}
}