tags/0.1/src/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.3/src/classes/DiscussionOverlayTopTest.cls
@IsTest private class DiscussionOverlayTopTest {
    
    
    public static String TEAMID =null;
    
    public static testMethod void testDiscussion() {
            
        DiscussionForum__c team = new DiscussionForum__c();
        
        if(TEAMID != null){
             try {
                team = [SELECT
                        Team__r.Name, 
                        Team__c,
                        Id 
                        FROM DiscussionForum__c WHERE Team__c =: TEAMID LIMIT 1];
                        
             } catch (Exception e) {
                
                System.Debug('\n ///////////////////////////// \n Error , no team assigned \n //////////////////////////// \n The Forum ID is :' + TEAMID + '\n //////////////////////////// \n');
                
             }
                             
        } else {
            System.assert(TEAMID==null,'No existe Team ID');
            team = null;
        }
    }
}