trunk/src/objects/Competency__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/EducationHistory__c.object
<CustomObject>
    <fields>
        <fullName>DateAttendedFrom__c</fullName>
        <label>Date Attended From</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DateAttendedTo__c</fullName>
        <label>Date Attended To</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>School</description>
        <inlineHelpText>School</inlineHelpText>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Education History</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.2/src/objects/Employer__c.object
<CustomObject>
    <description>Store the employers of every user.</description>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Employer</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.1/src/objects/EmploymentHistory__c.object
<CustomObject>
    <fields>
        <fullName>Employer__c</fullName>
        <description>Employer</description>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Employment  History</relationshipLabel>
        <relationshipName>Employer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkedFrom__c</fullName>
        <label>Worked From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkedTo__c</fullName>
        <label>Worked To</label>
        <type>Date</type>
    </fields>
    <label>Employment  History</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment  History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.6/src/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/src/objects/PeopleSubscription__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>People Subscription</label>
    <nameField>
        <label>People Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.5/src/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.5/src/objects/UserCompetencies__c.object
<CustomObject>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <referenceTo>Competency__c</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Competencies</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Competencies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.6/src/classes/GenerateEnvironmentPeopleTest.cls
public class GenerateEnvironmentPeopleTest {

	public static testMethod void gen(){
		
		TeamUtil.isTest = true;
		
		Competency__c newComp = new Competency__c();
		newComp.Name = 'Test Competency';
		newComp.Count__c = 1;
		insert newComp;
		
		// Create a new User
		Profile p = [select id from profile where name='System Administrator'];
		User newUser = new User(alias = 'standt', email='standarduser@testorg.com', 
								emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
								localesidkey='en_US', profileid = p.Id, 
								timezonesidkey='America/Los_Angeles', username='standarduser@testorg.com');
		insert newUser;
		
		UserCompetencies__c userComp = new UserCompetencies__c();
		userComp.Competency__c = newComp.Id;
		userComp.User__c = newUser.Id;//UserInfo.getUserId();
		userComp.Name = 'Test User Competency';
		userComp.rating__c = 5;
		insert userComp;
		
        Employer__c emp = new Employer__c();
		emp.Name = 'Test Employer';
		emp.Count__c = 1;
		insert emp;
		
		EmploymentHistory__c empHist = new EmploymentHistory__c();
		empHist.Employer__c = emp.Id;
		empHist.User__c = newUser.Id;
		empHist.Name = 'Test Employment History';
		empHist.WorkedFrom__c = System.today();
		empHist.WorkedTo__c = System.today();
		insert empHist;	
		
		PeopleProfile__c peopProf = new PeopleProfile__c();
		peopProf.User__c = UserInfo.getUserId();
		peopProf.Name = 'Test People Profile';
		insert peopProf;
		
        School__c scl = new School__c();
		scl.Name = 'Test School';
		scl.Count__c = 1;
		insert scl;
		
		EducationHistory__c educHist = new EducationHistory__c();
		educHist.School__c = scl.Id;
		educHist.User__c = newUser.Id;//UserInfo.getUserId();
		educHist.Name = 'Test Education History'; 
		educHist.DateAttendedTo__c = 0;
		educHist.DateAttendedFrom__c = 0;
		insert educHist;
		
		PeopleSubscription__c peopSubs = new PeopleSubscription__c();
		peopSubs.Person__c = newUser.Id;//UserInfo.getUserId();
		peopSubs.Name = 'Test People Subscription';
		insert peopSubs;
	}

}