trunk/src/objects/Competency__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/UserCompetencies__c.object
<CustomObject>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <referenceTo>Competency__c</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Competencies</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Competencies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.6/src/classes/PeopleNewEditCompetencyTest.cls
@IsTest private class PeopleNewEditCompetencyTest {
    public static testMethod void testPeople() {
        try{        
			GenerateEnvironmentPeopleTest.gen();
			Test.startTest();

            ApexPages.StandardController controller ;
            PeopleNewEditCompetencyController people= new PeopleNewEditCompetencyController(controller);
            
            people.setUserId(UserInfo.getUserId());
            people.init();
            User u = people.getNewUser();
            PeopleProfile__c peopleProfile = people.getMySidebarProfile();
        
            PeopleNewEditCompetencyController.Status status = new PeopleNewEditCompetencyController.Status();
            DateTime now = System.now();
            status.setModified(now);
            String modif = status.getModified();
            status = people.getStatus();            
            
            String s = people.getCurrentTime();
            String pic = people.getMyPicture();
            Boolean showStat = people.getShowStatus();
            Boolean isNew = people.getIsNewRecord();
            
            PeopleNewEditCompetencyController.PeopleSearch ps = people.getPeopleSearchObj();            
            ps.setKeyword('word');
            String keyWord = ps.getKeyword();
                        
            people.getCompetency();
            Competency__c c = people.getNewCompetency();
            String s1 = people.getNameCompetency();
            String s2 = people.getReturnRating();
            String s3 = people.getError();
            UserCompetencies__c userCompetency = people.getNewUserCompetency();
            
            people.setNameCompetency('Competency Name');
            PageReference page1 = people.saveCompetency();               

            Competency__c comp = [select id, Name from Competency__c limit 1];
            people.setNewCompetency(comp);
            
            //UserCompetencies__c userComp = [select Id, Name, User__c from UserCompetencies__c order by createdDate desc limit 1];
            
            Competency__c newComp = new Competency__c() ;
			newComp.Name = 'Test Competency';			
			newComp.Count__c = 1;
			insert newComp;
            
            UserCompetencies__c userComp = new UserCompetencies__c();
            userComp.Competency__c = newComp.Id;
			userComp.User__c = UserInfo.getUserId();
			userComp.rating__c = 5;
			insert userComp;	
            
            people.setNewUserCompetency(userComp);
            people.setNameCompetency('');
            PageReference page8 = people.saveCompetency();

            Competency__c comp2 = new Competency__c();
            comp2.Name = 'Competency Name 2'; 
            people.setNewCompetency(comp2);
            PageReference page7 = people.saveCompetency();
            
            PageReference page6 = people.saveAndNewCompetency();
            
            people.setUserCompId(userComp.Id);
            PageReference page2 = people.deleteCompetency();
            
            PageReference page3 = people.cancel();
            PageReference page4 = people.forwardTo('/apex/TeamsOverview');
            PageReference page5 = people.cancelCompetency();
            PageReference page9 = people.findPeople();
            
			Test.stopTest();
        }catch(Exception e){
            throw e;
        }
    }
}