trunk/src/objects/Competency__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/EducationHistory__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>School</description>
        <inlineHelpText>School</inlineHelpText>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Education History</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/Employer__c.object
<CustomObject>
    <description>Store the employers of every user.</description>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Employer</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/EmploymentHistory__c.object
<CustomObject>
    <fields>
        <fullName>Employer__c</fullName>
        <description>Employer</description>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Employment  History</relationshipLabel>
        <relationshipName>Employer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Employment  History</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment  History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/MiniFeed__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EducationHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmploymentHistory__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UserCompetencies__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamspaceMember__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DiscussionThread__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Announcement__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProjectTask__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlogEntry__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WikiPage__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookmark__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamNew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEdit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamDelete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberLeave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberAdd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamMemberJoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditRole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TeamEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCreateNewType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminEditType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneType</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminNewTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdminCloneTeamProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleAddNewUser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEditProfile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeoplePhoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEducationChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleEmploymentChange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleCompetencyChange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MiniFeed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mini Feed</label>
    <nameField>
        <label>Mini Feed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mini Feeds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Current Profile Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusLastModifiedDate__c</fullName>
        <description>Status Last Modified Date</description>
        <inlineHelpText>Status Last Modified Date</inlineHelpText>
        <label>StatusLastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/src/objects/PeopleSubscription__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>People Subscription</label>
    <nameField>
        <label>People Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/UserCompetencies__c.object
<CustomObject>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <referenceTo>Competency__c</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Competencies</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Competencies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/classes/PeopleOverviewController.cls
public class PeopleOverviewController {
	
	// Send current time (aprox)
	//  	
	public String getCurrentTime(){
		Datetime now = (System.now()).addHours(7);
		String s1 = now.format('yyyy-MM-dd');
		String s2 = now.format('HH:mm:ss.SSS');
		String dateString = s1 + 'T' + s2 + 'Z';
		return dateString;
	}

	/**
	* Return the Namespace Prefix
	*/
	public String getNamespace () {
        return TeamUtil.getNamespace();
    } 
    	
	// Constructor
	public PeopleOverviewController(){}
	
	/**
	* Check if people profile exist for current user
	*@return PageReference
	*/
	public PageReference profileExist(){
		PageReference pr = null;
		List<PeopleProfile__c> profiles = new List<PeopleProfile__c>();
		profiles = getPeopleProfile();
		if(profiles.size() == 0){
			PeopleProfile__c profile = new PeopleProfile__c();
			profile.User__c = UserInfo.getUserId();
			profile.Name = UserInfo.getName();
			insert profile;
		}
		return pr;
	}
	
	/**
	* Get people profile for current user
	*@return List<PeopleProfile__c>
	*/
	public List<PeopleProfile__c> getPeopleProfile(){
		List<PeopleProfile__c> profiles = new List<PeopleProfile__c>();			
		profiles = [SELECT Id,  Status__c, Picture__c, StatusLastModifiedDate__c
		     		FROM PeopleProfile__c
		     		WHERE User__c =: UserInfo.getUserId()];
		return profiles;	
	}
				
	//####################################//
	// New Faces
	//####################################//
	
	public List<People> getNewFaces(){
 		List<PeopleProfile__c> tempList = [SELECT Id,
 												User__c,
                                                User__r.Name,
                                                User__r.Division,
                                                User__r.Department,                                                
                                                User__r.Title,
                                                Picture__c,                                               
                                                CreatedDate                                                
                                        		FROM PeopleProfile__c
                                         		ORDER BY User__r.CreatedDate DESC LIMIT 5 ];
                                         		
        List<People> newPeopleList = new List<People>();
		for(PeopleProfile__c p: tempList){
			People person = new People();
			person.setUserId(p.User__c);
			person.setUsername(p.User__r.Name);
			person.setDivision(p.User__r.Division);
			person.setDepartment(p.User__r.Department);
			person.setTitle(p.User__r.Title);
			if((p.Picture__c == '') || (p.Picture__c == null)){
				person.setImageId('');
			} else{
				person.setImageId(p.Picture__c);
			}
			newPeopleList.add(person);
		}
		return newPeopleList;
	}
	
	public class People {
		String UserId;
        String Username;
        String Division;
        String Department;
        String Title;
        String ImageId;	
		
		public String getUserId() {
            return UserId;
        }
        
        public void setUserId(String UserId) {
            this.UserId = UserId;
        }		
		
        public String getUsername() {
            return Username;
        }
        
        public void setUsername(String Username) {
            this.Username = Username;
        }
        
        public String getDivision() {
            return Division;
        }
        
        public void setDivision(String Division) {
            this.Division = Division;
        }
        
        public String getDepartment() {
            return Department;
        }
        
        public void setDepartment(String Department) {
            this.Department = Department;
        }
        
        public String getTitle() {
            return Title;
        }
        
        public void setTitle(String Title) {
            this.Title = Title;
        }
		
		public String getImageId() {
            return ImageId;
        }
        
        public void setImageId(String ImageId) {
            this.ImageId = ImageId;
        }
		
    }
    
    /** 
   	* Profile picture attachment methods
   	*/	  	  
	
	public Attachment peopleAttach = new Attachment();
	public Integer AttachmentSize { get; set;}
	
	public void setPeopleAttach (Attachment attach) {
		this.peopleAttach = attach;
	}
	
	public Attachment getPeopleAttach () {     
		return peopleAttach;
	}

	public PageReference profileGallery (){
		String pageRoute = '/apex/peoplephotogallery?pid='+gallerypid;
		PageReference pageRef = new PageReference(pageRoute);
		return pageRef;
	}
	
	public String gallerypid = System.currentPageReference().getParameters().get('pid');
	public Integer getCountUploads(){
		Integer countuploads = 0;
		if(System.currentPageReference().getParameters().get('upc') != '' && System.currentPageReference().getParameters().get('upc') != null){
			countuploads = Integer.valueOf(System.currentPageReference().getParameters().get('upc'));
		}
		return countuploads;
	}
	public PageReference savePeopleAttach(){
		if((AttachmentSize > 5000000) || !(checkMimeType()) ){			
			peopleAttach = new Attachment();
			PageReference pageRef = new PageReference('/apex/PeopleUploadPicture?pid='+System.currentPageReference().getParameters().get('pid')+'&upstate=false&upc='+this.getCountUploads());
			pageRef.setRedirect(true);
			return pageRef;
		} else {
			peopleAttach.ParentId = System.currentPageReference().getParameters().get('pid');
			PageReference pageRef = new PageReference('/apex/PeopleUploadPicture?pid='+peopleAttach.ParentId+'&upstate=true&upc='+(this.getCountUploads()+1));
			pageRef.setRedirect(true);
			insert peopleAttach;
			return pageRef;
		}				
				
	} 
	
	public String ContentType { get; set;}
	
	public Boolean checkMimeType(){		
		Map<String, String> typesMime = new Map<String, String>{
       			'image/jpeg' => 'images.gif', 
       			'image/pjpeg' => 'images.gif', 
       			'image/png' => 'images.gif', 
       			'image/x-png' => 'images.gif', 
       			'image/gif' => 'images.gif', 
       			'image/bmp' => 'images.gif'       			
   			};
		if(typesMime.containsKey(ContentType)){
			return true;
		} else {
			return false;
		}	
	}
	
	public boolean displayError {get; set;} 
	
	public boolean successMessage { get; set; }
	
	public void initAttachmentCheck(){
		displayError = false;
		//Check if the parameter are there
		if(System.currentPageReference().getParameters().get('upstate') == 'false'){
			displayError = true;		
		} else if (System.currentPageReference().getParameters().get('upstate') == 'true'){
			successMessage = true;
		}
	}

	
	//####################################//
	// People Keyword Search 
	//####################################//
	
	//Search Result Page 
    private static String PEOPLE_SEARCH_RESULTS_PAGE = '/apex/PeopleKeywordSearchResults';
    
    //Search Object Initialization
    PeopleSearch peopleSearchObj = new PeopleSearch();    
    
    public PeopleSearch getPeopleSearchObj (){
        return peopleSearchObj;
   	}
        
    public PageReference findPeople() {
        PageReference pageRef = new PageReference(PEOPLE_SEARCH_RESULTS_PAGE
                      							+ '?keyword=' + peopleSearchObj.getKeyword());
        pageRef.setRedirect(true);
        return pageRef;
    }
          
	public class PeopleSearch {
	        
        String Keyword;       

        public String getKeyword() {
                return Keyword;
        }

        public void setKeyword(String Keyword) {
                this.Keyword = Keyword;
        }        
	}
	
	//####################################//
	// Tag Clouds 
	//####################################//
	
	// Competencies Cloud
	public List<CloudItems> getCompetenciesCloud(){
		List<CloudItems> competencyCloud = generateCloud('Competency');
		return competencyCloud;	
	}
		
	// Former Companies Cloud
	public List<CloudItems> getFormerCompaniesCloud(){
		List<CloudItems> competencyCloud = generateCloud('Employer');
		return competencyCloud;		
	}
	
	// Colleges Cloud
	public List<CloudItems> getCollegesCloud(){
		List<CloudItems> competencyCloud = generateCloud('School');
		return competencyCloud;
	}
	
	
	public List<CloudItems> generateCloud(String CloudType){
		// Build the list 
		List<CloudItems> queryResults = new List<CloudItems>(); 
		
		if(CloudType == 'Employer'){
			List<Employer__c> l = new List<Employer__c>();
			// Select the values from database
			l = [Select Name, Count__c From Employer__c ORDER BY Count__c DESC LIMIT 15];
			for(Employer__c e: l){
				CloudItems c = new CloudItems();
				c.setName(e.Name);
				c.setCount(e.Count__c);
				queryResults.add(c);
			}
		}
		if(CloudType == 'School'){
			List<School__c> l = new List<School__c>();
			// Select the values from database
			l = [Select Name, Count__c From School__c ORDER BY Count__c DESC LIMIT 15];
			for(School__c e: l){
				CloudItems c = new CloudItems();
				c.setName(e.Name);
				c.setCount(e.Count__c);
				queryResults.add(c);
			}
		}
		if(CloudType == 'Competency'){
			List<Competency__c> l = new List<Competency__c>();
			// Select the values from database
			l = [Select Name, Count__c From Competency__c ORDER BY Count__c DESC LIMIT 15];
			for(Competency__c e: l){
				CloudItems c = new CloudItems();
				c.setName(e.Name);
				c.setCount(e.Count__c);
				queryResults.add(c);
			}
		}
		if(queryResults.size() == 0) return queryResults;
				
		// Get the highest rated item     
		Double maxRating = queryResults[0].Count;
		
		// Get the fraction
		Double base = maxRating / 10;
		
		// Level build
		Double level_1 = base ;
		Double level_2 = base * 2;
		Double level_3 = base * 3;
		Double level_4 = base * 4;
		Double level_5 = base * 5;
		Double level_6 = base * 6;
		Double level_7 = base * 7;
		Double level_8 = base * 8;
		Double level_9 = base * 9;
		Double level_10 = base * 10;
		
		// Build list
		List<CloudItems> result = new List<CloudItems>(); 
		
		for(CloudItems e: queryResults){
				CloudItems item = new CloudItems();
		     	item.setName(e.Name);		     	
		     	if (e.Count < level_1) 
		     		item.setLevel(1);
		     	if (e.Count >= level_1 && e.Count < level_2) 
		     		item.setLevel(2);
		     	if (e.Count >= level_2 && e.Count < level_3) 
		     		item.setLevel(3);
		     	if (e.Count >= level_3 && e.Count < level_4) 
		     		item.setLevel(4);
		     	if (e.Count >= level_4 && e.Count < level_5) 
		     		item.setLevel(5);
		     	if (e.Count >= level_5 && e.Count < level_6) 
		     		item.setLevel(6);
		     	if (e.Count >= level_6 && e.Count < level_7) 
		     		item.setLevel(7);
		     	if (e.Count >= level_7 && e.Count < level_8) 
		     		item.setLevel(8);
		     	if (e.Count >= level_8 && e.Count < level_9) 
		     		item.setLevel(9);
		     	if (e.Count >= level_9 && e.Count < level_10) 
		     		item.setLevel(10);
		     	result.add(item);		     	
		}
		
		// Shuffle
		Integer resultSize = result.size() - 1;
	    Integer i;	    
	  
	    for (i = 0; i <= resultSize; i++) {
	        Integer alea = Integer.valueOf(String.valueOf(Math.roundToLong(Math.ceil(Math.random() * resultSize))));
	        CloudItems item;
	 		item = result.get(i);
	 		result.set(i, result.get(alea));
	 		result.set(alea, item); 
	    	}
		return result; 
	}
	
	public class CloudItems { 		
 		String Name;
 		Integer Level;
 		Double Count;

        public String getName () {
        	return Name;       	
        } 
                
        public void setName (String Name) {
        	this.Name = Name;
        }
        
        public Integer getLevel () {
        	return Level;
        }   
        
        public void setLevel (Integer Level) {
        	this.Level = Level;
        }       	
        
        public double getCount () {
        	return Count;
        }   
        
        public void setCount (double Count) {
        	this.Count = Count;
        }    
 	}
 	
 	
	//####################################//
	// Mini Feeds
	//####################################//
	// Show feeds ?
    boolean showFeeds = true;
	
	public boolean getShowFeeds(){
	    	return showFeeds;
	}
	   
     public List<miniFeed> getMiniFeeds() {
     	
     	
       	// Feed Dates 
		boolean TodayShow = false;
	   	boolean YesterdayShow = false ;
	    boolean monthShow = false ;
	    DateTime now = System.now();
	    String dateAlreadyShown = '';
	    String FeedParsedDate = '';
	    Datetime FeedDateIterator;
	    
     	List<miniFeed> miniFeeds = new List<miniFeed>();
     	
     	if (miniFeeds.size() < 1) {
			List<MiniFeed__c> feeds;
			List<String> subscribedList = new List<String>();
			List<PeopleSubscription__c> subsAux = new List<PeopleSubscription__c>();
			
			subsAux = [Select p.Subscriber__c, p.Person__c, p.Person__r.Id From PeopleSubscription__c p where p.Subscriber__c =: UserInfo.getUserId()];
			
			if(subsAux.size() > 0){
				showFeeds = true;
				for(PeopleSubscription__c ps: subsAux){
					subscribedList.add(ps.Person__r.Id);
				} 	
			} 
			if(subscribedList.size() > 0){
				feeds =  [Select
									m.User__c,
									m.User__r.Name, 
									m.Type__c, 
									m.Message__c,
									m.CreatedDate 
									From MiniFeed__c m  				
									WHERE User__c IN: subscribedList ORDER BY m.CreatedDate DESC LIMIT 10];
									
				for(Integer i = 0; i < feeds.size() ; i++){
					miniFeed miniFeed = new miniFeed();
					miniFeed.setUser(feeds[i].User__c);
                    miniFeed.setName(feeds[i].User__r.Name);
                    miniFeed.setMessage(feeds[i].Message__c);
                    miniFeed.setTypeOfFeed(feeds[i].Type__c);
                    miniFeed.setFeedDate(feeds[i].CreatedDate);
             
                    // Set the Date Message 
					FeedDateIterator = feeds[i].CreatedDate;
					FeedParsedDate = 'Date' + FeedDateIterator.day() + FeedDateIterator.month() + FeedDateIterator.year();	        		
                   	
	        		// Check if today is the day
	        		if( ( FeedDateIterator.day() == now.day() ) && ( !TodayShow )){
	        			TodayShow = true;
	        			miniFeed.setFeedDateClass('miniFeedDate');
	        			miniFeed.setFeedDateString('Today');						        			       
	        		} else {
	        			// Yesterday 
	        			if ((FeedDateIterator.day() == ( now.day() - 1 )) && (!YesterdayShow )) {
	        				YesterdayShow = true;
	        				miniFeed.setFeedDateClass('miniFeedDate');
	        				miniFeed.setFeedDateString('Yesterday');	        				
	        			} else {
	        				if ( FeedDateIterator.day() == now.day()){
	        					miniFeed.setFeedDateClass('miniFeedDate_empty');
	        					miniFeed.setFeedDateString(' ');
	        				} else {					        			
		        				if ( dateAlreadyShown != FeedParsedDate ){      					
		        					String Month;
		        					if( FeedDateIterator.month() == 1) 
		        						Month = 'January ';
		        					if( FeedDateIterator.month() == 2) 
		        						Month = 'February ';
		        					if( FeedDateIterator.month() == 3) 
		        						Month = 'March  ';
		        					if( FeedDateIterator.month() == 4) 
		        						Month = 'April '; 
		        					if( FeedDateIterator.month() == 5) 
		        						Month = 'May '; 
		        					if( FeedDateIterator.month() == 6) 
		        						Month = 'June '; 
		        					if( FeedDateIterator.month() == 7) 
		        						Month = 'July '; 
		        					if( FeedDateIterator.month() == 8) 
		        						Month = 'August '; 
		        					if( FeedDateIterator.month() == 9) 
		        						Month = 'September '; 
		        					if( FeedDateIterator.month() == 10) 
		        						Month = 'October '; 
		        					if( FeedDateIterator.month() == 11) 
		        						Month = 'November '; 
		        					if( FeedDateIterator.month() == 12) 
		        						Month = 'December '; 
		        					
		        					dateAlreadyShown = 'Date' + FeedDateIterator.day() + FeedDateIterator.month() + FeedDateIterator.year();
		        					String tempDate = Month + FeedDateIterator.day() + ', ' + FeedDateIterator.year();
		        					miniFeed.setFeedDateClass('miniFeedDate');
		        					miniFeed.setFeedDateString(tempDate);
		        				} else {
		        					miniFeed.setFeedDateClass('miniFeedDate_empty');
		        					miniFeed.setFeedDateString('');
		        				}
	        				}
	        			}  		
	        		}    
                    miniFeeds.add(miniFeed);    
				}					
			}    					
		                                
 		}
    	return miniFeeds;
    } 
    					
	public class miniFeed {
		
		public String User;
		public String Name;
        public String TypeOfFeed;
        public String Message;
        public String FeedDateString;
        public String FeedDateClass;
        public Datetime FeedDate;        
        
      	public miniFeed(){	
      		
      	}
      	
      	// Icon of the current type 
        public String getTypeOfFeed() {
    			if (TypeOfFeed == 'EducationHistory__c') 
    				TypeOfFeed = 'education'; 
        		if (TypeOfFeed == 'UserCompetencies__c') 
        			TypeOfFeed = 'competency';
        		if (TypeOfFeed == 'DiscussionThread__c') 
        			TypeOfFeed = 'discussion';
        		if (TypeOfFeed == 'EmploymentHistory__c') 
        			TypeOfFeed = 'employment';
        		if (TypeOfFeed == 'Announcement__c') 
        			TypeOfFeed = 'announcement';
        		if (TypeOfFeed == 'TeamspaceMember__c') 
        			TypeOfFeed = 'teamspace';
        		
        		return TypeOfFeed;
			}
			
			public void setTypeOfFeed(String sTypeOfFeed){
                TypeOfFeed = sTypeOfFeed;
	        }
      
	      	public String getName() {
                return Name;
	        }
	        
	        public void setName(String sName){
                Name = sName;
	        }
	        
	        public String getUser() {
	            return User;
	        }
	        
	        public void setUser(String sUser){
                User = sUser;
	        }
	        
	        public String getMessage() {
	        	return Message;
	        }
	        
	        public void setMessage(String sMessage){
                Message = sMessage;
	        }
	       	
	        public Datetime getFeedDate() {
	        	return FeedDate;
		        		       
	        }
	        
	        public void setFeedDate(Datetime sFeedDate){
                FeedDate = sFeedDate;
	        }  
	        
	       	public String getFeedDateString() {
	        	return FeedDateString;
		        		       
	        }
	        
	        public void setFeedDateString(String sFeedDateString){
                FeedDateString = sFeedDateString;
	        }  
	        
	        public String getFeedDateClass() {
	        	return FeedDateClass;
	        }
	        
	        public void setFeedDateClass(String sFeedDateClass){
                FeedDateClass = sFeedDateClass;
	        }  
	}	
}