trunk/src/objects/Competency__c.object
<CustomObject>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competency</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/EducationHistory__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <description>School</description>
        <inlineHelpText>School</inlineHelpText>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Education History</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/Employer__c.object
<CustomObject>
    <description>Store the employers of every user.</description>
    <label>Employer</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/EmploymentHistory__c.object
<CustomObject>
    <fields>
        <fullName>Employer__c</fullName>
        <description>Employer</description>
        <label>Employer</label>
        <referenceTo>Employer__c</referenceTo>
        <relationshipLabel>Employment  History</relationshipLabel>
        <relationshipName>Employer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Employment  History</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment  History</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>AboutMe__c</fullName>
        <label>About Me</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Aol__c</fullName>
        <label>Aol</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Current Profile Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skype__c</fullName>
        <label>Skype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YahooIM__c</fullName>
        <label>YahooIM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.1/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>25</length>
        <type>Text</type>
    </fields>

0.1/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamRelationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/UserCompetencies__c.object
<CustomObject>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <referenceTo>Competency__c</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserCompetencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Competencies</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Competencies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.1/src/classes/PeopleKeywordSearchController.cls
public class PeopleKeywordSearchController{	

	//Generate Instance of PaginatorController Class
	protected PaginatorController paginator = new PaginatorController();
	protected String title;
	protected boolean myPeople = false;
	
	//User Id 
	protected String userId = Userinfo.getUserId();
	
	public void setUserId(String sUserid){
		userId = sUserid;
	}
	
	protected Integer SizeList = 0;
	
	// Primary Set to store result values
	public Set<String> results = new Set<String>();
	
	//@@ Get Parameters      
	public String getParam(String nameParam){
		return System.currentPageReference().getParameters().get(nameParam);
	}
        
    //@@ Like Parameters 
    public String likeParam(String nameParam){
                    return '%' + nameParam + '%';
    }
       
    //@@ Parameter is empty        
    public boolean paramIsEmpty(String parameterName) {

		String parameterValue = getParam(parameterName);

		boolean emptyParam = false;
        	if (parameterValue == null) {
            	emptyParam = true;
        	} else {
            	if (parameterValue.equals('')) {
                	emptyParam = true;
                	}
        	}
        	return emptyParam;
    }
    
	
	/* -------- */
   	/*  SETTERS */
   	/* -------- */
	
	
	//Set Size of List
	public Void setSizeList(Integer size)
	{
		SizeList = size;
	}

	
	//GET Generic List of Pepole Profile
	public List<PeopleProfile__c> getPeople()
	{
		return result;
	}
	
	//GET Instance of Class PaginatorController
	public PaginatorController getPaginator()
	{
		return paginator;
	}
	
	//GET Size of List
	public Integer getSizeList()
	{
		return SizeList;
	}
	
	
	//Constructor Default
	public PeopleKeywordSearchController() {
		ResultCore('Search');	
	
	}
	
	/* ---------------------------- */
   	/*  Public Atributes for Layout */
   	/* ---------------------------- */
   	// Get Tilte for page.
   	public String getTitle () 
   	{
   		return title;
   	}
   	
   	
   	public static final String KEYWORD = 'keyword';	
	
	public String getKeyword(){
		return getParam(KEYWORD);
	}
	
	public String typeAction = 'Search';
	
	public String getTypeAction(){
		return typeAction;
	}
	
   	/* ------------ */
   	/*  Result Core */
   	/* ------------ */
	//List of PeopleProfile__c 
	List<PeopleProfile__c> result = new List<PeopleProfile__c>();
	
	String keywordString = '';
	
	public void setKeywordString (String sKey){
		keywordString = sKey;
	} 
	
	//ResultCore()
	// @String type { result binding} 
	public void ResultCore(String TypeA)
	{
			
		if(!(paramIsEmpty(KEYWORD))){
			keywordString = System.currentPageReference().getParameters().get('keyword');
		}
		TypeA = 'Search';
		if(userId == null)
		{
			userId = Userinfo.getUserId();
			myPeople = true;
		}
	 	
 		// Declarations
       	List<User> nameSearch = new List<User>();
       	List<User> allUsers = new List<User>();
    	List<EmploymentHistory__c> formerJobSearch = new List<EmploymentHistory__c>(); 
    	List<EducationHistory__c> collegeSearch = new List<EducationHistory__c>();
    	List<UserCompetencies__c> competencySearch = new List<UserCompetencies__c>();
    	List<TeamMember__c> teamspaceSearch = new List<TeamMember__c>();		
			
		// Search lists
		if(keywordString != ''){
			
			nameSearch = [select id from User WHERE Name LIKE :likeParam(keywordString)];		        	
	    	formerJobSearch = [select User__c from EmploymentHistory__c WHERE Employer__r.Name LIKE :likeParam(keywordString) ];
	    	collegeSearch = [select User__c from EducationHistory__c WHERE School__r.Name LIKE :likeParam(keywordString) ];
	    	competencySearch = [select User__c from UserCompetencies__c WHERE Competency__r.Name LIKE :likeParam(keywordString) ];
	    	teamspaceSearch = [select User__c from TeamMember__c WHERE Team__r.Name LIKE :likeParam(keywordString) ];
			
			
			if(nameSearch.size() > 0 ) {
	        	for(User userId:nameSearch){
	        		results.add(userId.id);
	        	}
        	}
        
			/// Former Job List ////
	        	       		
			if(formerJobSearch.size() > 0){
	        	for(EmploymentHistory__c userId:formerJobSearch){        		
	        			results.add(userId.User__c);        		 		
	        	}        	 			
			}	        		

	    	/// College List ///
	    	
       		if(collegeSearch.size() > 0){    			
        		for(EducationHistory__c userId:collegeSearch){	        		
	        			results.add(userId.User__c);	        		  		
	        	} 	        
    		}

	    	/// Competency List ///
    		if(competencySearch.size() > 0){    		
	        	for(UserCompetencies__c userId:competencySearch){	        		
	        			results.add(userId.User__c);	        				
	        	} 	        	
    		}
	    	    	
	    	/// Teamspace List ///
			if(teamspaceSearch.size() > 0){			
	    		for(TeamMember__c userId:teamspaceSearch){        	
	        			results.add(userId.User__c);        		 		
	        	}         	
			}

		} else {
			
			// Get all users, no keyword given
			allusers = [SELECT Id FROM User];
			
			for(User userId:allusers){        	
	        		results.add(userId.Id);        		 		
	        	}
		
		}
			
		List<Id> users = new List<Id>();
		// Convert the Set to a list for Pagination	
		for(String r:results){
			users.add(r);			
		}	
			
			
				result = [Select p.YahooIM__c, 
 						 p.Aol__c,
	 					 p.User__r.Phone, 
	 					 p.User__r.Email, 
	 					 p.User__r.Title, 
	 					 p.User__r.Department, 
	 					 p.User__r.Division, 
	 					 p.User__r.CompanyName, 
	 					 p.User__r.Name,
	 					 p.User__r.Id, 
	 					 p.User__c, 
	 					 p.Skype__c, 
	 					 p.Picture__c, 
	 					 p.AboutMe__c
	 					 From PeopleProfile__c p where p.User__c in : users
	 					 order by p.User__r.Name asc ];	
			
	 	
	 	
		 	//Set the Values of Paginator
		 	setSizeList(result.size());
		 	paginator.serTotalItemsNumber(result.size());
		 	paginator.genCntPagination();
		 	
		 	title = 'Search Results from People';	 	
	   		
	 	}
	 	
}