trunk/src/objects/PeopleSubscription__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <label>Subscriber</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>People Subscription</label>
    <nameField>
        <label>People Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

trunk/main/src/classes/PeopleSuscribeControllerTest.cls
@IsTest private class PeopleSuscribeControllerTest {
    public static testMethod void test() {
        try{
			GenerateEnvironmentTest.gen();
            Test.startTest(); 
		
			PeopleSuscribeController suscribe = new PeopleSuscribeController();

			PeopleSubscription__c ps = new PeopleSubscription__c();
			ps.Name = 'Test';
			ps.Person__c = UserInfo.getUserId();
			ps.Subscriber__c = UserInfo.getUserId();
			insert ps;
			
			suscribe.setPersonId(UserInfo.getUserId());
			suscribe.getPersonId();
			suscribe.getCurrentId();
			suscribe.getIsCurrentUser();
			
			suscribe.getSubscriptionStatus();
			suscribe.Subscribe();
			suscribe.getSubscribedBoolean();
			suscribe.getSubscribedName();
			suscribe.getSubsRow();
			suscribe.Subscribe();

            Test.stopTest(); 
        }catch(Exception e){
            throw e;
        }
    } 
}