trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateBlogs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateBlogs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateBookmarks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateBookmarks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateDiscussionTopics__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateDiscussionTopics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateProjectTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateProjectTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateWikiPages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateWikiPages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageAttachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Property used to control the permissions of the Team Profile with the management of the attachments.</description>
        <label>ManageAttachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageBookmarks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageBookmarks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageDiscussionForums__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageDiscussionForums</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageProjectTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageProjectTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageTeams__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageTeams</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ManageWikis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManageWikis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostBlogComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostBlogComments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostBookmarkComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostBookmarkComments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostDiscussionTopicReplies__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostDiscussionTopicReplies</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostWikiComments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PostWikiComments</label>
        <type>Checkbox</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.3/src/objects/Widget__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Gadget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widget</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WidgetUrl__c</fullName>
        <label>WidgetUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

branches/0.5/src/classes/InitializeTeamspacesController.cls
public class InitializeTeamspacesController {

	//Action history
	public Boolean alreadyRun {get; set;}
	public Boolean insertWidget {get; set;}
	public Boolean insertProfiles {get; set;}
	
	
	//Asoc. widget name with component name
	static final Map<String, String> widgets  = new Map<String, String>{'Attachments' => 'TeamsWidgetAttachments', 
																		'Tasks' => 'TeamsWidgetTasksMain',
																		'Recent WikiPages' => 'TeamsWidgetRecentWikiPages', 
																		'Recent Activities' => 'TeamsWidgetRecentActivities',
																		'Active Discussions' => 'TeamsWidgetActiveDiscussions',
																		'Milestones' => 'TeamsWidgetMilestones', 
																		'Wiki Directory' => 'TeamsWidgetWikiDirectory'};
	//Default profiles
	static final Set<String> profiles = new Set<String> {'Team Administrator', 'Read Only', 'Individual Contributor'};
	
	public InitializeTeamspacesController(){
		//Only for Admin use
		TeamUtil.isAdminMemberUser();
		
		alreadyRun = false;
	}
	
	/**
	* Initialize
	*@void
	*/
	public void initialize(){

		insertWidget = false;
		insertProfiles = false;

		/* ### Default Widgets ### */
		List<Widget__c> widgetList = new List<Widget__c>();
		Set<String> widgetNames = new Set<String>();
		
		widgetList = [select w.Id, w.Name, WidgetUrl__c from Widget__c w where w.Type__c = 'Widget'];
		for(Widget__c widget : widgetList)
			widgetNames.add(widget.Name);	
		
		Widget__c newWidget;
		widgetList.clear();
		
		for(String widgetName : widgets.keySet()){
			if(!widgetNames.contains(widgetName)){
				newWidget = new Widget__c();	
				newWidget.Name = widgetName;
				newWidget.WidgetUrl__c = widgets.get(widgetName);
				newWidget.Type__c = 'Widget';
				System.debug('\n --- Add Widget:' + widgetName + '--- \n');
				widgetList.add(newWidget);
			}
		}
		
		if(widgetList.size() > 0){
			insertWidget = true;
			insert widgetList;
		}
		
		/* ### Default Profiles ###*/
		List<TeamProfile__c> profilesList = new List<TeamProfile__c>();
		Set<String> profilesNames = new Set<String>(); 
		
		profilesList = [select p.Id, p.Name from TeamProfile__c p];
		for(TeamProfile__c profile : profilesList)
			profilesNames.add(profile.Name);
			 
		for(String profileName : profiles){
			if(!profilesNames.contains(profileName)){
				createProfile(profileName);	
			}
		}
		
		alreadyRun = true;
	}
	
	/**
	* Create profile
	*@void
	*/
	public void createProfile (String name){
		
		TeamProfile__c profile = new TeamProfile__c(); 
		if(name == 'Team Administrator'){
			profile.Name = name;
			profile.ManageAttachments__c = true;
			profile.ManageProjectTasks__c = true;
			profile.ManageTeams__c = true;
			profile.ManageBookmarks__c = true;
			profile.ManageDiscussionForums__c = true;
			profile.PostBookmarkComments__c = true;
			profile.PostDiscussionTopicReplies__c = true;
			profile.CreateBookmarks__c = true;
			profile.CreateDiscussionTopics__c = true;
			profile.CreateWikiPages__c = true;
			profile.PostBlogComments__c = true;
			profile.ManageWikis__c = true;
			profile.PostWikiComments__c = true;
			profile.CreateProjectTasks__c = true;
			profile.CreateBlogs__c = true;
		}else if (name == 'Read Only'){
			profile.Name = name;
		}else if (name == 'Individual Contributor'){
			profile.Name = name;
			profile.PostDiscussionTopicReplies__c = true;
			profile.CreateDiscussionTopics__c = true;
			profile.CreateWikiPages__c = true;
			profile.PostWikiComments__c = true;
			profile.CreateProjectTasks__c = true;
		}
		
		if(profile.Name != null){
			System.debug('\n --- Add profile:' + profile.Name + '--- \n');
			insertProfiles = true;
			insert profile;
		}
	}

}