0.1/src/objects/Bookmark__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BookmarkURL__c</fullName>
        <label>Bookmark Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Comment Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Bookmarks</relationshipLabel>
        <relationshipName>Bookmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>imageUrl__c</fullName>
        <label>imageUrl</label>
        <type>Url</type>
    </fields>
    <label>Bookmark</label>
    <nameField>
        <label>Bookmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Comment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/0.1/src/objects/Comment__c.object
    <fields>
        <fullName>Bookmark__c</fullName>
        <label>Parent Bookmark</label>
        <referenceTo>Bookmark__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>ParentBookmark</relationshipName>
        <type>Lookup</type>
    </fields>

trunk/objects/DiscussionForum__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Discussion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forum Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/objects/PeopleProfile__c.object
<CustomObject>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Current Profile Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>People Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.1/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/Team__c.object
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <length>25</length>
        <type>Text</type>
    </fields>

0.1/src/classes/BookmarkDetailController.cls
public class BookmarkDetailController {
	// COLLABSUITE-883
	Bookmark__c bookmark;
	
	 Comment__c newComment;
	
	public BookmarkDetailController(ApexPages.StandardController controller) {
    	bookmark = (Bookmark__c)controller.getRecord();
    	
    	// I am going to query the datebase for the information 
    	// that should already be in the bookmark object b/c at
    	// the time of writing this code the stardcontroller overide has some
    	// issues.  When it gets over it issues you can delete this block of
    	// code
    	bookmark = [SELECT Title__c, 
    							
    						   Body__c,
    						   Team__c,
    						   Team__r.Name,
    						   Comments__c,
    						 //   Comment__c,
							   BookmarkURL__c,
							   ImageUrl__c,
    						   CreatedDate,
    						   CreatedById
    					FROM Bookmark__c
    					WHERE Id =: bookmark.Id];
    	
    	// newComment = new Comment__c(Bookmark__c = bookmark.Id);
    }
    
    public String getPostedDate() {
    	return bookmark.CreatedDate.format('MMMM dd, yyyy');    	
    }
    
    public List<Comment> getComments() {
    	
    	List<Comment__c> comments = [SELECT Id,
    									    Message__c, 
    									    CreatedDate, 
    									    CreatedById
    								 FROM Comment__c
    								 WHERE Bookmark__c =: bookmark.Id
    								 ORDER BY CreatedDate ASC];
    	// Get list of users
    	
    	Set<Id> users = new Set<Id>();
    							 
    	for(Comment__c c: comments) {
    		users.add(c.CreatedById);
    	}
    	
    	Map<Id, Id> userProfileMap = new Map<Id, Id>();
    	for(PeopleProfile__c p: [SELECT Picture__c,
    									User__c
    							 FROM PeopleProfile__c
    							 WHERE User__c IN: users]) {
    		userProfileMap.put(p.User__c, p.Picture__c);						 	
    	}
    	
    	List<Comment> commentWrappers = new List<Comment>();
    	
    	// create comments wrapper
    	for(Comment__c c: comments) {
    		commentWrappers.add(new Comment(c, userProfileMap.get(c.CreatedById)));
    	}
    	
    	return commentWrappers;
    }

    
    public class Comment {
    	
    	Comment__c comment;
    	Id imageId;
    	
    	public Comment(Comment__c c, Id i) {
    		comment = c;
    		imageId = i;
    	}
    	
    	public String getFormatedCommentDate() {
    		return comment.CreatedDate.format('MMM dd, yyyy');
    	}
    	
    	public String getFormatedCommentTime() {
    		return comment.CreatedDate.format('hh:mm aa');
    	}
    	
    	public Id getUserImageId() {
    		if(imageId == null) return '01530000000VO5s';
		    else             return imageId;
    	}

    	public Comment__c getDetail() {
    		return comment;
    	}
    }

   
    public PageReference savePost() {
    	
    	// Refresh the new comment object for the next post
    	newComment = new Comment__c(Bookmark__c = bookmark.Id);
    	insert newComment;
    	// Increment the count for display
    	// The trigger updates the database
    	bookmark.Comments__c += 1;
    	
    	return null;
    }
    
    public Comment__c getNewComment() {
    	return newComment;
    } 
	
	
}