0.1/src/objects/Bookmark__c.object
<CustomObject>
    <fields>
        <fullName>PostedDate__c</fullName>
        <label>Posted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Bookmarks</relationshipLabel>
        <relationshipName>Bookmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bookmark</label>
    <nameField>
        <label>Bookmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

0.1/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

0.1/src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>TeamProfile__c</fullName>
        <label>Team Profile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamRelationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TeamProfile__c.object
<CustomObject>
    <fields>
        <fullName>CreateBookmarks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateBookmarks</label>
        <type>Checkbox</type>
    </fields>
    <label>Team Profile</label>
    <nameField>
        <label>Team Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

0.1/src/classes/TeamWidgetRecentBookmarkController.cls
public class TeamWidgetRecentBookmarkController {
	// Get Team Id Attribute
	
	String teamIdBook;
	
	// Setter method for Team Id variable
	public void setTeamIdBook(String tID) {
		teamIdBook = tID;		
	}
	
	public String getTeamIdBook(){
		return teamIdBook;
	}
  
  	 Integer BookmarksCount;
  	 String userId = UserInfo.getUserId();
  
     public List<Bookmark__c> getBookmarks() {
	    List<Bookmark__c> myBookmarks = new List<Bookmark__c>();	
		myBookmarks =  [Select  b.Title__c, 
								b.PostedDate__c, 
								b.CreatedBy.Name, 
								b.CreatedBy.Id, 
								b.CreatedById ,
								b.Team__c
						From 
								Bookmark__c b
						where 	b.Team__c =: teamIdBook
						order by b.PostedDate__c desc
						limit 8
						];
						
						
		
		
		BookmarksCount = myBookmarks.size();
    	return myBookmarks;
    } 
    
     public Integer getBookmarksCount(){
	        return BookmarksCount;
    }
    
    public void setblogCount(Integer count){
    	BookmarksCount = count;
    	
    }
	
	//Boolean for previlieges to create
	  public Boolean getnewPrivileges() {
    	List<TeamMember__c> tm = new List<TeamMember__c>();	
    	tm  = [Select 
    					t.User__c, 
    					t.Team__c, 
    					t.TeamProfile__r.CreateBookmarks__c, 
    					t.TeamProfile__c From TeamMember__c t 
    					where t.Team__c =: teamIdBook and t.User__c =: userId ];
		Boolean result;
		if(tm == null){
			result = false;
			return result;
		}
		else {
			result = tm[0].TeamProfile__r.CreateBookmarks__c;
			return result;
		}
    }       
    					
}