0.1/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

0.1/src/classes/TeamsWidgetWikiDirectoryController.cls
public class TeamsWidgetWikiDirectoryController {

	
	// Get Team Id Attribute
	String teamId;
	
    // Setter method for Team Id variable
	public void setTeamId(String tID) {
		teamId = tID;		
	}
	
	public String getTeamId(){
		return teamId;
	}
	
	Integer wikiPagesCount;
    

	public class Wikis {
	
		WikiPage__c wikiPage;
		String name;
		String createdByName;
		
		public Wikis (WikiPage__c wiki) {
			wikiPage = wiki;
		}
		
		public WikiPage__c getWikiPage () {
			return wikiPage;
		}
		
		public String getName () {
			String trunkName = wikiPage.Name;
			if(wikiPage.Name.length() > 17) {
				trunkName = wikiPage.Name.substring(0,17) + '..';
			}
			return trunkName; 
		}
		
		public String getCreatedByName () {
			String trunkCreatedByName = wikiPage.CreatedBy.Name;
			if(wikiPage.CreatedBy.Name.length() > 17) {
				trunkCreatedByName = wikiPage.CreatedBy.Name.substring(0,17) + '..';
			}
			return trunkCreatedByName; 
		}
	}

    
    
    public List<Wikis> getWikis() {
		List<WikiPage__c> wikis = new List<WikiPage__c>();
	   	wikis =  [Select Team__c,
					 LastModifiedDate ,
					 Name, Id, 
					 CreatedBy.Name, 
					 CreatedBy.Id, 
					 CreatedById
					 From WikiPage__c  
					 Where Team__c =: teamId and Parent__c = ''
					 ORDER BY Name ASC limit 100];
 		
 		List<Wikis> resultWikis = new List<Wikis>();
 		
 		for (WikiPage__c item: wikis) {
 			Wikis itemWiki = new Wikis(item);
 			resultWikis.add(itemWiki);
 		}
 		
 		wikiPagesCount = wikis.size();
 		return resultWikis;
    } 
    
     public Integer getWikiPagesCount(){
    	return wikiPagesCount;
    }
    
    public void setWikiPagesCount(Integer count){
    	wikiPagesCount = count;
    }
    
    public void refresh() {
    	System.debug('\n ////////////////////////////////////// \n REFRESH \n //////////////////////////////// \n');
    }
    	
}