branches/0.5/src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>NewMemberProfile__c</fullName>
        <label>NewMemberProfile</label>
        <referenceTo>TeamProfile__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.3/src/classes/TeamsDetailTest.cls
@IsTest private class TeamsDetailTest {
    
    public static String USERID =  UserInfo.getUserId();
    
    public static testMethod void testTeam() {
        try{
            TeamsDetailController team = new TeamsDetailController();
            Team__c t = [select Id from Team__c where NewMemberProfile__c != '' limit 1];
            team.setTeamIdParam(t.Id);
            team.getTeamDetail();
            t = team.getTeamspace();
            team.joinTeam();
            team.leaveTeam();
            Boolean open = team.getTeamIsOpen();
            String param = team.getTeamIdParam();
            Boolean message = team.getShowJoinTeamMessage();
            team.assignShowJoinTeamMessage();
            UserPermissions up = team.getUserPermissionsWiki();
            String image = team.getTeamspaceImage();
        }catch(Exception e){
            throw e;
        }
    }
}