branches/0.5/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.1/src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.1/src/classes/TeamsWidgetWikiController.cls
public class TeamsWidgetWikiController {


	Id teamspaceId;
	
	public TeamsWidgetWikiController() {
		teamspaceId = System.currentPageReference().getParameters().get('id');
	}
	
	public Id getTeamspaceId() {
		return teamspaceId;
	}
	
	public List<WikiPage__c> getWikiPages() {
		
		if(teamspaceId==null) return new List<WikiPage__c>();
		
		List<WikiPage__c> pages = [SELECT Name
									   FROM WikiPage__c
									   WHERE Team__c =: teamspaceId
									   ORDER BY LastModifiedDate DESC
									   LIMIT 5];
		
		return pages;
	}
	
	
	public Integer getWikiPagesSize(){
		List<WikiPage__c> wikis = getWikiPages();
		
		return wikis.size();		
	}

}