branches/0.5/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

branches/0.1/src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Wiki</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <label>Wiki Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

branches/0.1/src/classes/TeamsWidgetRecentWikiPagesController.cls
public class TeamsWidgetRecentWikiPagesController {
	
	
	// Get Team Id Attribute
	String teamId;
	
	// Setter method for Team Id variable
	public void setTeamId(String tID) {
		teamId = tID;		
	}
	
	public String getTeamId(){
		return teamId;
	}
	
	Integer wikiPagesCount;
    
    
    public List<WikiPage__c> getWikis() {
     	
       	// Wikis
	    List<WikiPage__c> myWikis = new List<WikiPage__c>();
	    myWikis =  [Select Team__c,
					 LastModifiedDate ,
					 Name, Id, 
					 CreatedBy.Name, 
					 CreatedBy.Id, 
					 CreatedById
					 From WikiPage__c  
					 Where Team__c =: teamId
					 ORDER BY Name ASC LIMIT 10];
		                                
 		
 		wikiPagesCount = myWikis.size();
    	return myWikis;
    } 
    
     public Integer getWikiPagesCount(){
    	return wikiPagesCount;
    }
    
    public void setWikiPagesCount(Integer count){
    	wikiPagesCount = count;
    }
	       
    					
	
}